// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ClockMock implements mm_utils_time.Clock
type ClockMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcNow          func() (t1 time.Time)
	funcNowOrigin    string
	inspectFuncNow   func()
	afterNowCounter  uint64
	beforeNowCounter uint64
	NowMock          mClockMockNow
}

// NewClockMock returns a mock for mm_utils_time.Clock
func NewClockMock(t minimock.Tester) *ClockMock {
	m := &ClockMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.NowMock = mClockMockNow{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mClockMockNow struct {
	optional           bool
	mock               *ClockMock
	defaultExpectation *ClockMockNowExpectation
	expectations       []*ClockMockNowExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ClockMockNowExpectation specifies expectation struct of the Clock.Now
type ClockMockNowExpectation struct {
	mock *ClockMock

	results      *ClockMockNowResults
	returnOrigin string
	Counter      uint64
}

// ClockMockNowResults contains results of the Clock.Now
type ClockMockNowResults struct {
	t1 time.Time
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmNow *mClockMockNow) Optional() *mClockMockNow {
	mmNow.optional = true
	return mmNow
}

// Expect sets up expected params for Clock.Now
func (mmNow *mClockMockNow) Expect() *mClockMockNow {
	if mmNow.mock.funcNow != nil {
		mmNow.mock.t.Fatalf("ClockMock.Now mock is already set by Set")
	}

	if mmNow.defaultExpectation == nil {
		mmNow.defaultExpectation = &ClockMockNowExpectation{}
	}

	return mmNow
}

// Inspect accepts an inspector function that has same arguments as the Clock.Now
func (mmNow *mClockMockNow) Inspect(f func()) *mClockMockNow {
	if mmNow.mock.inspectFuncNow != nil {
		mmNow.mock.t.Fatalf("Inspect function is already set for ClockMock.Now")
	}

	mmNow.mock.inspectFuncNow = f

	return mmNow
}

// Return sets up results that will be returned by Clock.Now
func (mmNow *mClockMockNow) Return(t1 time.Time) *ClockMock {
	if mmNow.mock.funcNow != nil {
		mmNow.mock.t.Fatalf("ClockMock.Now mock is already set by Set")
	}

	if mmNow.defaultExpectation == nil {
		mmNow.defaultExpectation = &ClockMockNowExpectation{mock: mmNow.mock}
	}
	mmNow.defaultExpectation.results = &ClockMockNowResults{t1}
	mmNow.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmNow.mock
}

// Set uses given function f to mock the Clock.Now method
func (mmNow *mClockMockNow) Set(f func() (t1 time.Time)) *ClockMock {
	if mmNow.defaultExpectation != nil {
		mmNow.mock.t.Fatalf("Default expectation is already set for the Clock.Now method")
	}

	if len(mmNow.expectations) > 0 {
		mmNow.mock.t.Fatalf("Some expectations are already set for the Clock.Now method")
	}

	mmNow.mock.funcNow = f
	mmNow.mock.funcNowOrigin = minimock.CallerInfo(1)
	return mmNow.mock
}

// Times sets number of times Clock.Now should be invoked
func (mmNow *mClockMockNow) Times(n uint64) *mClockMockNow {
	if n == 0 {
		mmNow.mock.t.Fatalf("Times of ClockMock.Now mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmNow.expectedInvocations, n)
	mmNow.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmNow
}

func (mmNow *mClockMockNow) invocationsDone() bool {
	if len(mmNow.expectations) == 0 && mmNow.defaultExpectation == nil && mmNow.mock.funcNow == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmNow.mock.afterNowCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmNow.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Now implements mm_utils_time.Clock
func (mmNow *ClockMock) Now() (t1 time.Time) {
	mm_atomic.AddUint64(&mmNow.beforeNowCounter, 1)
	defer mm_atomic.AddUint64(&mmNow.afterNowCounter, 1)

	mmNow.t.Helper()

	if mmNow.inspectFuncNow != nil {
		mmNow.inspectFuncNow()
	}

	if mmNow.NowMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNow.NowMock.defaultExpectation.Counter, 1)

		mm_results := mmNow.NowMock.defaultExpectation.results
		if mm_results == nil {
			mmNow.t.Fatal("No results are set for the ClockMock.Now")
		}
		return (*mm_results).t1
	}
	if mmNow.funcNow != nil {
		return mmNow.funcNow()
	}
	mmNow.t.Fatalf("Unexpected call to ClockMock.Now.")
	return
}

// NowAfterCounter returns a count of finished ClockMock.Now invocations
func (mmNow *ClockMock) NowAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNow.afterNowCounter)
}

// NowBeforeCounter returns a count of ClockMock.Now invocations
func (mmNow *ClockMock) NowBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNow.beforeNowCounter)
}

// MinimockNowDone returns true if the count of the Now invocations corresponds
// the number of defined expectations
func (m *ClockMock) MinimockNowDone() bool {
	if m.NowMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NowMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NowMock.invocationsDone()
}

// MinimockNowInspect logs each unmet expectation
func (m *ClockMock) MinimockNowInspect() {
	for _, e := range m.NowMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to ClockMock.Now")
		}
	}

	afterNowCounter := mm_atomic.LoadUint64(&m.afterNowCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NowMock.defaultExpectation != nil && afterNowCounter < 1 {
		m.t.Errorf("Expected call to ClockMock.Now at\n%s", m.NowMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNow != nil && afterNowCounter < 1 {
		m.t.Errorf("Expected call to ClockMock.Now at\n%s", m.funcNowOrigin)
	}

	if !m.NowMock.invocationsDone() && afterNowCounter > 0 {
		m.t.Errorf("Expected %d calls to ClockMock.Now at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NowMock.expectedInvocations), m.NowMock.expectedInvocationsOrigin, afterNowCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ClockMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockNowInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ClockMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ClockMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockNowDone()
}
