// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/PlayingPossumHiss/possum_chat/internal/entity"
	"github.com/gojuno/minimock/v3"
)

// ConfigStorageMock implements mm_message_queue.ConfigStorage
type ConfigStorageMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcConfig          func() (c1 entity.Config)
	funcConfigOrigin    string
	inspectFuncConfig   func()
	afterConfigCounter  uint64
	beforeConfigCounter uint64
	ConfigMock          mConfigStorageMockConfig
}

// NewConfigStorageMock returns a mock for mm_message_queue.ConfigStorage
func NewConfigStorageMock(t minimock.Tester) *ConfigStorageMock {
	m := &ConfigStorageMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ConfigMock = mConfigStorageMockConfig{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mConfigStorageMockConfig struct {
	optional           bool
	mock               *ConfigStorageMock
	defaultExpectation *ConfigStorageMockConfigExpectation
	expectations       []*ConfigStorageMockConfigExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ConfigStorageMockConfigExpectation specifies expectation struct of the ConfigStorage.Config
type ConfigStorageMockConfigExpectation struct {
	mock *ConfigStorageMock

	results      *ConfigStorageMockConfigResults
	returnOrigin string
	Counter      uint64
}

// ConfigStorageMockConfigResults contains results of the ConfigStorage.Config
type ConfigStorageMockConfigResults struct {
	c1 entity.Config
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmConfig *mConfigStorageMockConfig) Optional() *mConfigStorageMockConfig {
	mmConfig.optional = true
	return mmConfig
}

// Expect sets up expected params for ConfigStorage.Config
func (mmConfig *mConfigStorageMockConfig) Expect() *mConfigStorageMockConfig {
	if mmConfig.mock.funcConfig != nil {
		mmConfig.mock.t.Fatalf("ConfigStorageMock.Config mock is already set by Set")
	}

	if mmConfig.defaultExpectation == nil {
		mmConfig.defaultExpectation = &ConfigStorageMockConfigExpectation{}
	}

	return mmConfig
}

// Inspect accepts an inspector function that has same arguments as the ConfigStorage.Config
func (mmConfig *mConfigStorageMockConfig) Inspect(f func()) *mConfigStorageMockConfig {
	if mmConfig.mock.inspectFuncConfig != nil {
		mmConfig.mock.t.Fatalf("Inspect function is already set for ConfigStorageMock.Config")
	}

	mmConfig.mock.inspectFuncConfig = f

	return mmConfig
}

// Return sets up results that will be returned by ConfigStorage.Config
func (mmConfig *mConfigStorageMockConfig) Return(c1 entity.Config) *ConfigStorageMock {
	if mmConfig.mock.funcConfig != nil {
		mmConfig.mock.t.Fatalf("ConfigStorageMock.Config mock is already set by Set")
	}

	if mmConfig.defaultExpectation == nil {
		mmConfig.defaultExpectation = &ConfigStorageMockConfigExpectation{mock: mmConfig.mock}
	}
	mmConfig.defaultExpectation.results = &ConfigStorageMockConfigResults{c1}
	mmConfig.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmConfig.mock
}

// Set uses given function f to mock the ConfigStorage.Config method
func (mmConfig *mConfigStorageMockConfig) Set(f func() (c1 entity.Config)) *ConfigStorageMock {
	if mmConfig.defaultExpectation != nil {
		mmConfig.mock.t.Fatalf("Default expectation is already set for the ConfigStorage.Config method")
	}

	if len(mmConfig.expectations) > 0 {
		mmConfig.mock.t.Fatalf("Some expectations are already set for the ConfigStorage.Config method")
	}

	mmConfig.mock.funcConfig = f
	mmConfig.mock.funcConfigOrigin = minimock.CallerInfo(1)
	return mmConfig.mock
}

// Times sets number of times ConfigStorage.Config should be invoked
func (mmConfig *mConfigStorageMockConfig) Times(n uint64) *mConfigStorageMockConfig {
	if n == 0 {
		mmConfig.mock.t.Fatalf("Times of ConfigStorageMock.Config mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmConfig.expectedInvocations, n)
	mmConfig.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmConfig
}

func (mmConfig *mConfigStorageMockConfig) invocationsDone() bool {
	if len(mmConfig.expectations) == 0 && mmConfig.defaultExpectation == nil && mmConfig.mock.funcConfig == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmConfig.mock.afterConfigCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmConfig.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Config implements mm_message_queue.ConfigStorage
func (mmConfig *ConfigStorageMock) Config() (c1 entity.Config) {
	mm_atomic.AddUint64(&mmConfig.beforeConfigCounter, 1)
	defer mm_atomic.AddUint64(&mmConfig.afterConfigCounter, 1)

	mmConfig.t.Helper()

	if mmConfig.inspectFuncConfig != nil {
		mmConfig.inspectFuncConfig()
	}

	if mmConfig.ConfigMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmConfig.ConfigMock.defaultExpectation.Counter, 1)

		mm_results := mmConfig.ConfigMock.defaultExpectation.results
		if mm_results == nil {
			mmConfig.t.Fatal("No results are set for the ConfigStorageMock.Config")
		}
		return (*mm_results).c1
	}
	if mmConfig.funcConfig != nil {
		return mmConfig.funcConfig()
	}
	mmConfig.t.Fatalf("Unexpected call to ConfigStorageMock.Config.")
	return
}

// ConfigAfterCounter returns a count of finished ConfigStorageMock.Config invocations
func (mmConfig *ConfigStorageMock) ConfigAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmConfig.afterConfigCounter)
}

// ConfigBeforeCounter returns a count of ConfigStorageMock.Config invocations
func (mmConfig *ConfigStorageMock) ConfigBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmConfig.beforeConfigCounter)
}

// MinimockConfigDone returns true if the count of the Config invocations corresponds
// the number of defined expectations
func (m *ConfigStorageMock) MinimockConfigDone() bool {
	if m.ConfigMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ConfigMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ConfigMock.invocationsDone()
}

// MinimockConfigInspect logs each unmet expectation
func (m *ConfigStorageMock) MinimockConfigInspect() {
	for _, e := range m.ConfigMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to ConfigStorageMock.Config")
		}
	}

	afterConfigCounter := mm_atomic.LoadUint64(&m.afterConfigCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ConfigMock.defaultExpectation != nil && afterConfigCounter < 1 {
		m.t.Errorf("Expected call to ConfigStorageMock.Config at\n%s", m.ConfigMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcConfig != nil && afterConfigCounter < 1 {
		m.t.Errorf("Expected call to ConfigStorageMock.Config at\n%s", m.funcConfigOrigin)
	}

	if !m.ConfigMock.invocationsDone() && afterConfigCounter > 0 {
		m.t.Errorf("Expected %d calls to ConfigStorageMock.Config at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ConfigMock.expectedInvocations), m.ConfigMock.expectedInvocationsOrigin, afterConfigCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ConfigStorageMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockConfigInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ConfigStorageMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ConfigStorageMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockConfigDone()
}
