// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/PlayingPossumHiss/possum_chat/internal/entity"
	"github.com/gojuno/minimock/v3"
)

// YoutubeClientMock implements mm_youtube_scraper.YoutubeClient
type YoutubeClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetLastTranslationID          func(ctx context.Context, userName string) (s1 string, err error)
	funcGetLastTranslationIDOrigin    string
	inspectFuncGetLastTranslationID   func(ctx context.Context, userName string)
	afterGetLastTranslationIDCounter  uint64
	beforeGetLastTranslationIDCounter uint64
	GetLastTranslationIDMock          mYoutubeClientMockGetLastTranslationID

	funcGetMessages          func() (ma1 []entity.Message, err error)
	funcGetMessagesOrigin    string
	inspectFuncGetMessages   func()
	afterGetMessagesCounter  uint64
	beforeGetMessagesCounter uint64
	GetMessagesMock          mYoutubeClientMockGetMessages

	funcInit          func(streamKey string) (err error)
	funcInitOrigin    string
	inspectFuncInit   func(streamKey string)
	afterInitCounter  uint64
	beforeInitCounter uint64
	InitMock          mYoutubeClientMockInit
}

// NewYoutubeClientMock returns a mock for mm_youtube_scraper.YoutubeClient
func NewYoutubeClientMock(t minimock.Tester) *YoutubeClientMock {
	m := &YoutubeClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetLastTranslationIDMock = mYoutubeClientMockGetLastTranslationID{mock: m}
	m.GetLastTranslationIDMock.callArgs = []*YoutubeClientMockGetLastTranslationIDParams{}

	m.GetMessagesMock = mYoutubeClientMockGetMessages{mock: m}

	m.InitMock = mYoutubeClientMockInit{mock: m}
	m.InitMock.callArgs = []*YoutubeClientMockInitParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mYoutubeClientMockGetLastTranslationID struct {
	optional           bool
	mock               *YoutubeClientMock
	defaultExpectation *YoutubeClientMockGetLastTranslationIDExpectation
	expectations       []*YoutubeClientMockGetLastTranslationIDExpectation

	callArgs []*YoutubeClientMockGetLastTranslationIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// YoutubeClientMockGetLastTranslationIDExpectation specifies expectation struct of the YoutubeClient.GetLastTranslationID
type YoutubeClientMockGetLastTranslationIDExpectation struct {
	mock               *YoutubeClientMock
	params             *YoutubeClientMockGetLastTranslationIDParams
	paramPtrs          *YoutubeClientMockGetLastTranslationIDParamPtrs
	expectationOrigins YoutubeClientMockGetLastTranslationIDExpectationOrigins
	results            *YoutubeClientMockGetLastTranslationIDResults
	returnOrigin       string
	Counter            uint64
}

// YoutubeClientMockGetLastTranslationIDParams contains parameters of the YoutubeClient.GetLastTranslationID
type YoutubeClientMockGetLastTranslationIDParams struct {
	ctx      context.Context
	userName string
}

// YoutubeClientMockGetLastTranslationIDParamPtrs contains pointers to parameters of the YoutubeClient.GetLastTranslationID
type YoutubeClientMockGetLastTranslationIDParamPtrs struct {
	ctx      *context.Context
	userName *string
}

// YoutubeClientMockGetLastTranslationIDResults contains results of the YoutubeClient.GetLastTranslationID
type YoutubeClientMockGetLastTranslationIDResults struct {
	s1  string
	err error
}

// YoutubeClientMockGetLastTranslationIDOrigins contains origins of expectations of the YoutubeClient.GetLastTranslationID
type YoutubeClientMockGetLastTranslationIDExpectationOrigins struct {
	origin         string
	originCtx      string
	originUserName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) Optional() *mYoutubeClientMockGetLastTranslationID {
	mmGetLastTranslationID.optional = true
	return mmGetLastTranslationID
}

// Expect sets up expected params for YoutubeClient.GetLastTranslationID
func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) Expect(ctx context.Context, userName string) *mYoutubeClientMockGetLastTranslationID {
	if mmGetLastTranslationID.mock.funcGetLastTranslationID != nil {
		mmGetLastTranslationID.mock.t.Fatalf("YoutubeClientMock.GetLastTranslationID mock is already set by Set")
	}

	if mmGetLastTranslationID.defaultExpectation == nil {
		mmGetLastTranslationID.defaultExpectation = &YoutubeClientMockGetLastTranslationIDExpectation{}
	}

	if mmGetLastTranslationID.defaultExpectation.paramPtrs != nil {
		mmGetLastTranslationID.mock.t.Fatalf("YoutubeClientMock.GetLastTranslationID mock is already set by ExpectParams functions")
	}

	mmGetLastTranslationID.defaultExpectation.params = &YoutubeClientMockGetLastTranslationIDParams{ctx, userName}
	mmGetLastTranslationID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetLastTranslationID.expectations {
		if minimock.Equal(e.params, mmGetLastTranslationID.defaultExpectation.params) {
			mmGetLastTranslationID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetLastTranslationID.defaultExpectation.params)
		}
	}

	return mmGetLastTranslationID
}

// ExpectCtxParam1 sets up expected param ctx for YoutubeClient.GetLastTranslationID
func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) ExpectCtxParam1(ctx context.Context) *mYoutubeClientMockGetLastTranslationID {
	if mmGetLastTranslationID.mock.funcGetLastTranslationID != nil {
		mmGetLastTranslationID.mock.t.Fatalf("YoutubeClientMock.GetLastTranslationID mock is already set by Set")
	}

	if mmGetLastTranslationID.defaultExpectation == nil {
		mmGetLastTranslationID.defaultExpectation = &YoutubeClientMockGetLastTranslationIDExpectation{}
	}

	if mmGetLastTranslationID.defaultExpectation.params != nil {
		mmGetLastTranslationID.mock.t.Fatalf("YoutubeClientMock.GetLastTranslationID mock is already set by Expect")
	}

	if mmGetLastTranslationID.defaultExpectation.paramPtrs == nil {
		mmGetLastTranslationID.defaultExpectation.paramPtrs = &YoutubeClientMockGetLastTranslationIDParamPtrs{}
	}
	mmGetLastTranslationID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetLastTranslationID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetLastTranslationID
}

// ExpectUserNameParam2 sets up expected param userName for YoutubeClient.GetLastTranslationID
func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) ExpectUserNameParam2(userName string) *mYoutubeClientMockGetLastTranslationID {
	if mmGetLastTranslationID.mock.funcGetLastTranslationID != nil {
		mmGetLastTranslationID.mock.t.Fatalf("YoutubeClientMock.GetLastTranslationID mock is already set by Set")
	}

	if mmGetLastTranslationID.defaultExpectation == nil {
		mmGetLastTranslationID.defaultExpectation = &YoutubeClientMockGetLastTranslationIDExpectation{}
	}

	if mmGetLastTranslationID.defaultExpectation.params != nil {
		mmGetLastTranslationID.mock.t.Fatalf("YoutubeClientMock.GetLastTranslationID mock is already set by Expect")
	}

	if mmGetLastTranslationID.defaultExpectation.paramPtrs == nil {
		mmGetLastTranslationID.defaultExpectation.paramPtrs = &YoutubeClientMockGetLastTranslationIDParamPtrs{}
	}
	mmGetLastTranslationID.defaultExpectation.paramPtrs.userName = &userName
	mmGetLastTranslationID.defaultExpectation.expectationOrigins.originUserName = minimock.CallerInfo(1)

	return mmGetLastTranslationID
}

// Inspect accepts an inspector function that has same arguments as the YoutubeClient.GetLastTranslationID
func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) Inspect(f func(ctx context.Context, userName string)) *mYoutubeClientMockGetLastTranslationID {
	if mmGetLastTranslationID.mock.inspectFuncGetLastTranslationID != nil {
		mmGetLastTranslationID.mock.t.Fatalf("Inspect function is already set for YoutubeClientMock.GetLastTranslationID")
	}

	mmGetLastTranslationID.mock.inspectFuncGetLastTranslationID = f

	return mmGetLastTranslationID
}

// Return sets up results that will be returned by YoutubeClient.GetLastTranslationID
func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) Return(s1 string, err error) *YoutubeClientMock {
	if mmGetLastTranslationID.mock.funcGetLastTranslationID != nil {
		mmGetLastTranslationID.mock.t.Fatalf("YoutubeClientMock.GetLastTranslationID mock is already set by Set")
	}

	if mmGetLastTranslationID.defaultExpectation == nil {
		mmGetLastTranslationID.defaultExpectation = &YoutubeClientMockGetLastTranslationIDExpectation{mock: mmGetLastTranslationID.mock}
	}
	mmGetLastTranslationID.defaultExpectation.results = &YoutubeClientMockGetLastTranslationIDResults{s1, err}
	mmGetLastTranslationID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetLastTranslationID.mock
}

// Set uses given function f to mock the YoutubeClient.GetLastTranslationID method
func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) Set(f func(ctx context.Context, userName string) (s1 string, err error)) *YoutubeClientMock {
	if mmGetLastTranslationID.defaultExpectation != nil {
		mmGetLastTranslationID.mock.t.Fatalf("Default expectation is already set for the YoutubeClient.GetLastTranslationID method")
	}

	if len(mmGetLastTranslationID.expectations) > 0 {
		mmGetLastTranslationID.mock.t.Fatalf("Some expectations are already set for the YoutubeClient.GetLastTranslationID method")
	}

	mmGetLastTranslationID.mock.funcGetLastTranslationID = f
	mmGetLastTranslationID.mock.funcGetLastTranslationIDOrigin = minimock.CallerInfo(1)
	return mmGetLastTranslationID.mock
}

// When sets expectation for the YoutubeClient.GetLastTranslationID which will trigger the result defined by the following
// Then helper
func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) When(ctx context.Context, userName string) *YoutubeClientMockGetLastTranslationIDExpectation {
	if mmGetLastTranslationID.mock.funcGetLastTranslationID != nil {
		mmGetLastTranslationID.mock.t.Fatalf("YoutubeClientMock.GetLastTranslationID mock is already set by Set")
	}

	expectation := &YoutubeClientMockGetLastTranslationIDExpectation{
		mock:               mmGetLastTranslationID.mock,
		params:             &YoutubeClientMockGetLastTranslationIDParams{ctx, userName},
		expectationOrigins: YoutubeClientMockGetLastTranslationIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetLastTranslationID.expectations = append(mmGetLastTranslationID.expectations, expectation)
	return expectation
}

// Then sets up YoutubeClient.GetLastTranslationID return parameters for the expectation previously defined by the When method
func (e *YoutubeClientMockGetLastTranslationIDExpectation) Then(s1 string, err error) *YoutubeClientMock {
	e.results = &YoutubeClientMockGetLastTranslationIDResults{s1, err}
	return e.mock
}

// Times sets number of times YoutubeClient.GetLastTranslationID should be invoked
func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) Times(n uint64) *mYoutubeClientMockGetLastTranslationID {
	if n == 0 {
		mmGetLastTranslationID.mock.t.Fatalf("Times of YoutubeClientMock.GetLastTranslationID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetLastTranslationID.expectedInvocations, n)
	mmGetLastTranslationID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetLastTranslationID
}

func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) invocationsDone() bool {
	if len(mmGetLastTranslationID.expectations) == 0 && mmGetLastTranslationID.defaultExpectation == nil && mmGetLastTranslationID.mock.funcGetLastTranslationID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetLastTranslationID.mock.afterGetLastTranslationIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetLastTranslationID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetLastTranslationID implements mm_youtube_scraper.YoutubeClient
func (mmGetLastTranslationID *YoutubeClientMock) GetLastTranslationID(ctx context.Context, userName string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmGetLastTranslationID.beforeGetLastTranslationIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetLastTranslationID.afterGetLastTranslationIDCounter, 1)

	mmGetLastTranslationID.t.Helper()

	if mmGetLastTranslationID.inspectFuncGetLastTranslationID != nil {
		mmGetLastTranslationID.inspectFuncGetLastTranslationID(ctx, userName)
	}

	mm_params := YoutubeClientMockGetLastTranslationIDParams{ctx, userName}

	// Record call args
	mmGetLastTranslationID.GetLastTranslationIDMock.mutex.Lock()
	mmGetLastTranslationID.GetLastTranslationIDMock.callArgs = append(mmGetLastTranslationID.GetLastTranslationIDMock.callArgs, &mm_params)
	mmGetLastTranslationID.GetLastTranslationIDMock.mutex.Unlock()

	for _, e := range mmGetLastTranslationID.GetLastTranslationIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGetLastTranslationID.GetLastTranslationIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetLastTranslationID.GetLastTranslationIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetLastTranslationID.GetLastTranslationIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetLastTranslationID.GetLastTranslationIDMock.defaultExpectation.paramPtrs

		mm_got := YoutubeClientMockGetLastTranslationIDParams{ctx, userName}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetLastTranslationID.t.Errorf("YoutubeClientMock.GetLastTranslationID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetLastTranslationID.GetLastTranslationIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userName != nil && !minimock.Equal(*mm_want_ptrs.userName, mm_got.userName) {
				mmGetLastTranslationID.t.Errorf("YoutubeClientMock.GetLastTranslationID got unexpected parameter userName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetLastTranslationID.GetLastTranslationIDMock.defaultExpectation.expectationOrigins.originUserName, *mm_want_ptrs.userName, mm_got.userName, minimock.Diff(*mm_want_ptrs.userName, mm_got.userName))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetLastTranslationID.t.Errorf("YoutubeClientMock.GetLastTranslationID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetLastTranslationID.GetLastTranslationIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetLastTranslationID.GetLastTranslationIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetLastTranslationID.t.Fatal("No results are set for the YoutubeClientMock.GetLastTranslationID")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGetLastTranslationID.funcGetLastTranslationID != nil {
		return mmGetLastTranslationID.funcGetLastTranslationID(ctx, userName)
	}
	mmGetLastTranslationID.t.Fatalf("Unexpected call to YoutubeClientMock.GetLastTranslationID. %v %v", ctx, userName)
	return
}

// GetLastTranslationIDAfterCounter returns a count of finished YoutubeClientMock.GetLastTranslationID invocations
func (mmGetLastTranslationID *YoutubeClientMock) GetLastTranslationIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetLastTranslationID.afterGetLastTranslationIDCounter)
}

// GetLastTranslationIDBeforeCounter returns a count of YoutubeClientMock.GetLastTranslationID invocations
func (mmGetLastTranslationID *YoutubeClientMock) GetLastTranslationIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetLastTranslationID.beforeGetLastTranslationIDCounter)
}

// Calls returns a list of arguments used in each call to YoutubeClientMock.GetLastTranslationID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetLastTranslationID *mYoutubeClientMockGetLastTranslationID) Calls() []*YoutubeClientMockGetLastTranslationIDParams {
	mmGetLastTranslationID.mutex.RLock()

	argCopy := make([]*YoutubeClientMockGetLastTranslationIDParams, len(mmGetLastTranslationID.callArgs))
	copy(argCopy, mmGetLastTranslationID.callArgs)

	mmGetLastTranslationID.mutex.RUnlock()

	return argCopy
}

// MinimockGetLastTranslationIDDone returns true if the count of the GetLastTranslationID invocations corresponds
// the number of defined expectations
func (m *YoutubeClientMock) MinimockGetLastTranslationIDDone() bool {
	if m.GetLastTranslationIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetLastTranslationIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetLastTranslationIDMock.invocationsDone()
}

// MinimockGetLastTranslationIDInspect logs each unmet expectation
func (m *YoutubeClientMock) MinimockGetLastTranslationIDInspect() {
	for _, e := range m.GetLastTranslationIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to YoutubeClientMock.GetLastTranslationID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetLastTranslationIDCounter := mm_atomic.LoadUint64(&m.afterGetLastTranslationIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetLastTranslationIDMock.defaultExpectation != nil && afterGetLastTranslationIDCounter < 1 {
		if m.GetLastTranslationIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to YoutubeClientMock.GetLastTranslationID at\n%s", m.GetLastTranslationIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to YoutubeClientMock.GetLastTranslationID at\n%s with params: %#v", m.GetLastTranslationIDMock.defaultExpectation.expectationOrigins.origin, *m.GetLastTranslationIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetLastTranslationID != nil && afterGetLastTranslationIDCounter < 1 {
		m.t.Errorf("Expected call to YoutubeClientMock.GetLastTranslationID at\n%s", m.funcGetLastTranslationIDOrigin)
	}

	if !m.GetLastTranslationIDMock.invocationsDone() && afterGetLastTranslationIDCounter > 0 {
		m.t.Errorf("Expected %d calls to YoutubeClientMock.GetLastTranslationID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetLastTranslationIDMock.expectedInvocations), m.GetLastTranslationIDMock.expectedInvocationsOrigin, afterGetLastTranslationIDCounter)
	}
}

type mYoutubeClientMockGetMessages struct {
	optional           bool
	mock               *YoutubeClientMock
	defaultExpectation *YoutubeClientMockGetMessagesExpectation
	expectations       []*YoutubeClientMockGetMessagesExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// YoutubeClientMockGetMessagesExpectation specifies expectation struct of the YoutubeClient.GetMessages
type YoutubeClientMockGetMessagesExpectation struct {
	mock *YoutubeClientMock

	results      *YoutubeClientMockGetMessagesResults
	returnOrigin string
	Counter      uint64
}

// YoutubeClientMockGetMessagesResults contains results of the YoutubeClient.GetMessages
type YoutubeClientMockGetMessagesResults struct {
	ma1 []entity.Message
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetMessages *mYoutubeClientMockGetMessages) Optional() *mYoutubeClientMockGetMessages {
	mmGetMessages.optional = true
	return mmGetMessages
}

// Expect sets up expected params for YoutubeClient.GetMessages
func (mmGetMessages *mYoutubeClientMockGetMessages) Expect() *mYoutubeClientMockGetMessages {
	if mmGetMessages.mock.funcGetMessages != nil {
		mmGetMessages.mock.t.Fatalf("YoutubeClientMock.GetMessages mock is already set by Set")
	}

	if mmGetMessages.defaultExpectation == nil {
		mmGetMessages.defaultExpectation = &YoutubeClientMockGetMessagesExpectation{}
	}

	return mmGetMessages
}

// Inspect accepts an inspector function that has same arguments as the YoutubeClient.GetMessages
func (mmGetMessages *mYoutubeClientMockGetMessages) Inspect(f func()) *mYoutubeClientMockGetMessages {
	if mmGetMessages.mock.inspectFuncGetMessages != nil {
		mmGetMessages.mock.t.Fatalf("Inspect function is already set for YoutubeClientMock.GetMessages")
	}

	mmGetMessages.mock.inspectFuncGetMessages = f

	return mmGetMessages
}

// Return sets up results that will be returned by YoutubeClient.GetMessages
func (mmGetMessages *mYoutubeClientMockGetMessages) Return(ma1 []entity.Message, err error) *YoutubeClientMock {
	if mmGetMessages.mock.funcGetMessages != nil {
		mmGetMessages.mock.t.Fatalf("YoutubeClientMock.GetMessages mock is already set by Set")
	}

	if mmGetMessages.defaultExpectation == nil {
		mmGetMessages.defaultExpectation = &YoutubeClientMockGetMessagesExpectation{mock: mmGetMessages.mock}
	}
	mmGetMessages.defaultExpectation.results = &YoutubeClientMockGetMessagesResults{ma1, err}
	mmGetMessages.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetMessages.mock
}

// Set uses given function f to mock the YoutubeClient.GetMessages method
func (mmGetMessages *mYoutubeClientMockGetMessages) Set(f func() (ma1 []entity.Message, err error)) *YoutubeClientMock {
	if mmGetMessages.defaultExpectation != nil {
		mmGetMessages.mock.t.Fatalf("Default expectation is already set for the YoutubeClient.GetMessages method")
	}

	if len(mmGetMessages.expectations) > 0 {
		mmGetMessages.mock.t.Fatalf("Some expectations are already set for the YoutubeClient.GetMessages method")
	}

	mmGetMessages.mock.funcGetMessages = f
	mmGetMessages.mock.funcGetMessagesOrigin = minimock.CallerInfo(1)
	return mmGetMessages.mock
}

// Times sets number of times YoutubeClient.GetMessages should be invoked
func (mmGetMessages *mYoutubeClientMockGetMessages) Times(n uint64) *mYoutubeClientMockGetMessages {
	if n == 0 {
		mmGetMessages.mock.t.Fatalf("Times of YoutubeClientMock.GetMessages mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetMessages.expectedInvocations, n)
	mmGetMessages.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetMessages
}

func (mmGetMessages *mYoutubeClientMockGetMessages) invocationsDone() bool {
	if len(mmGetMessages.expectations) == 0 && mmGetMessages.defaultExpectation == nil && mmGetMessages.mock.funcGetMessages == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetMessages.mock.afterGetMessagesCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetMessages.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetMessages implements mm_youtube_scraper.YoutubeClient
func (mmGetMessages *YoutubeClientMock) GetMessages() (ma1 []entity.Message, err error) {
	mm_atomic.AddUint64(&mmGetMessages.beforeGetMessagesCounter, 1)
	defer mm_atomic.AddUint64(&mmGetMessages.afterGetMessagesCounter, 1)

	mmGetMessages.t.Helper()

	if mmGetMessages.inspectFuncGetMessages != nil {
		mmGetMessages.inspectFuncGetMessages()
	}

	if mmGetMessages.GetMessagesMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetMessages.GetMessagesMock.defaultExpectation.Counter, 1)

		mm_results := mmGetMessages.GetMessagesMock.defaultExpectation.results
		if mm_results == nil {
			mmGetMessages.t.Fatal("No results are set for the YoutubeClientMock.GetMessages")
		}
		return (*mm_results).ma1, (*mm_results).err
	}
	if mmGetMessages.funcGetMessages != nil {
		return mmGetMessages.funcGetMessages()
	}
	mmGetMessages.t.Fatalf("Unexpected call to YoutubeClientMock.GetMessages.")
	return
}

// GetMessagesAfterCounter returns a count of finished YoutubeClientMock.GetMessages invocations
func (mmGetMessages *YoutubeClientMock) GetMessagesAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetMessages.afterGetMessagesCounter)
}

// GetMessagesBeforeCounter returns a count of YoutubeClientMock.GetMessages invocations
func (mmGetMessages *YoutubeClientMock) GetMessagesBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetMessages.beforeGetMessagesCounter)
}

// MinimockGetMessagesDone returns true if the count of the GetMessages invocations corresponds
// the number of defined expectations
func (m *YoutubeClientMock) MinimockGetMessagesDone() bool {
	if m.GetMessagesMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetMessagesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetMessagesMock.invocationsDone()
}

// MinimockGetMessagesInspect logs each unmet expectation
func (m *YoutubeClientMock) MinimockGetMessagesInspect() {
	for _, e := range m.GetMessagesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to YoutubeClientMock.GetMessages")
		}
	}

	afterGetMessagesCounter := mm_atomic.LoadUint64(&m.afterGetMessagesCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetMessagesMock.defaultExpectation != nil && afterGetMessagesCounter < 1 {
		m.t.Errorf("Expected call to YoutubeClientMock.GetMessages at\n%s", m.GetMessagesMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetMessages != nil && afterGetMessagesCounter < 1 {
		m.t.Errorf("Expected call to YoutubeClientMock.GetMessages at\n%s", m.funcGetMessagesOrigin)
	}

	if !m.GetMessagesMock.invocationsDone() && afterGetMessagesCounter > 0 {
		m.t.Errorf("Expected %d calls to YoutubeClientMock.GetMessages at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetMessagesMock.expectedInvocations), m.GetMessagesMock.expectedInvocationsOrigin, afterGetMessagesCounter)
	}
}

type mYoutubeClientMockInit struct {
	optional           bool
	mock               *YoutubeClientMock
	defaultExpectation *YoutubeClientMockInitExpectation
	expectations       []*YoutubeClientMockInitExpectation

	callArgs []*YoutubeClientMockInitParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// YoutubeClientMockInitExpectation specifies expectation struct of the YoutubeClient.Init
type YoutubeClientMockInitExpectation struct {
	mock               *YoutubeClientMock
	params             *YoutubeClientMockInitParams
	paramPtrs          *YoutubeClientMockInitParamPtrs
	expectationOrigins YoutubeClientMockInitExpectationOrigins
	results            *YoutubeClientMockInitResults
	returnOrigin       string
	Counter            uint64
}

// YoutubeClientMockInitParams contains parameters of the YoutubeClient.Init
type YoutubeClientMockInitParams struct {
	streamKey string
}

// YoutubeClientMockInitParamPtrs contains pointers to parameters of the YoutubeClient.Init
type YoutubeClientMockInitParamPtrs struct {
	streamKey *string
}

// YoutubeClientMockInitResults contains results of the YoutubeClient.Init
type YoutubeClientMockInitResults struct {
	err error
}

// YoutubeClientMockInitOrigins contains origins of expectations of the YoutubeClient.Init
type YoutubeClientMockInitExpectationOrigins struct {
	origin          string
	originStreamKey string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInit *mYoutubeClientMockInit) Optional() *mYoutubeClientMockInit {
	mmInit.optional = true
	return mmInit
}

// Expect sets up expected params for YoutubeClient.Init
func (mmInit *mYoutubeClientMockInit) Expect(streamKey string) *mYoutubeClientMockInit {
	if mmInit.mock.funcInit != nil {
		mmInit.mock.t.Fatalf("YoutubeClientMock.Init mock is already set by Set")
	}

	if mmInit.defaultExpectation == nil {
		mmInit.defaultExpectation = &YoutubeClientMockInitExpectation{}
	}

	if mmInit.defaultExpectation.paramPtrs != nil {
		mmInit.mock.t.Fatalf("YoutubeClientMock.Init mock is already set by ExpectParams functions")
	}

	mmInit.defaultExpectation.params = &YoutubeClientMockInitParams{streamKey}
	mmInit.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInit.expectations {
		if minimock.Equal(e.params, mmInit.defaultExpectation.params) {
			mmInit.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInit.defaultExpectation.params)
		}
	}

	return mmInit
}

// ExpectStreamKeyParam1 sets up expected param streamKey for YoutubeClient.Init
func (mmInit *mYoutubeClientMockInit) ExpectStreamKeyParam1(streamKey string) *mYoutubeClientMockInit {
	if mmInit.mock.funcInit != nil {
		mmInit.mock.t.Fatalf("YoutubeClientMock.Init mock is already set by Set")
	}

	if mmInit.defaultExpectation == nil {
		mmInit.defaultExpectation = &YoutubeClientMockInitExpectation{}
	}

	if mmInit.defaultExpectation.params != nil {
		mmInit.mock.t.Fatalf("YoutubeClientMock.Init mock is already set by Expect")
	}

	if mmInit.defaultExpectation.paramPtrs == nil {
		mmInit.defaultExpectation.paramPtrs = &YoutubeClientMockInitParamPtrs{}
	}
	mmInit.defaultExpectation.paramPtrs.streamKey = &streamKey
	mmInit.defaultExpectation.expectationOrigins.originStreamKey = minimock.CallerInfo(1)

	return mmInit
}

// Inspect accepts an inspector function that has same arguments as the YoutubeClient.Init
func (mmInit *mYoutubeClientMockInit) Inspect(f func(streamKey string)) *mYoutubeClientMockInit {
	if mmInit.mock.inspectFuncInit != nil {
		mmInit.mock.t.Fatalf("Inspect function is already set for YoutubeClientMock.Init")
	}

	mmInit.mock.inspectFuncInit = f

	return mmInit
}

// Return sets up results that will be returned by YoutubeClient.Init
func (mmInit *mYoutubeClientMockInit) Return(err error) *YoutubeClientMock {
	if mmInit.mock.funcInit != nil {
		mmInit.mock.t.Fatalf("YoutubeClientMock.Init mock is already set by Set")
	}

	if mmInit.defaultExpectation == nil {
		mmInit.defaultExpectation = &YoutubeClientMockInitExpectation{mock: mmInit.mock}
	}
	mmInit.defaultExpectation.results = &YoutubeClientMockInitResults{err}
	mmInit.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInit.mock
}

// Set uses given function f to mock the YoutubeClient.Init method
func (mmInit *mYoutubeClientMockInit) Set(f func(streamKey string) (err error)) *YoutubeClientMock {
	if mmInit.defaultExpectation != nil {
		mmInit.mock.t.Fatalf("Default expectation is already set for the YoutubeClient.Init method")
	}

	if len(mmInit.expectations) > 0 {
		mmInit.mock.t.Fatalf("Some expectations are already set for the YoutubeClient.Init method")
	}

	mmInit.mock.funcInit = f
	mmInit.mock.funcInitOrigin = minimock.CallerInfo(1)
	return mmInit.mock
}

// When sets expectation for the YoutubeClient.Init which will trigger the result defined by the following
// Then helper
func (mmInit *mYoutubeClientMockInit) When(streamKey string) *YoutubeClientMockInitExpectation {
	if mmInit.mock.funcInit != nil {
		mmInit.mock.t.Fatalf("YoutubeClientMock.Init mock is already set by Set")
	}

	expectation := &YoutubeClientMockInitExpectation{
		mock:               mmInit.mock,
		params:             &YoutubeClientMockInitParams{streamKey},
		expectationOrigins: YoutubeClientMockInitExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInit.expectations = append(mmInit.expectations, expectation)
	return expectation
}

// Then sets up YoutubeClient.Init return parameters for the expectation previously defined by the When method
func (e *YoutubeClientMockInitExpectation) Then(err error) *YoutubeClientMock {
	e.results = &YoutubeClientMockInitResults{err}
	return e.mock
}

// Times sets number of times YoutubeClient.Init should be invoked
func (mmInit *mYoutubeClientMockInit) Times(n uint64) *mYoutubeClientMockInit {
	if n == 0 {
		mmInit.mock.t.Fatalf("Times of YoutubeClientMock.Init mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInit.expectedInvocations, n)
	mmInit.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInit
}

func (mmInit *mYoutubeClientMockInit) invocationsDone() bool {
	if len(mmInit.expectations) == 0 && mmInit.defaultExpectation == nil && mmInit.mock.funcInit == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInit.mock.afterInitCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInit.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Init implements mm_youtube_scraper.YoutubeClient
func (mmInit *YoutubeClientMock) Init(streamKey string) (err error) {
	mm_atomic.AddUint64(&mmInit.beforeInitCounter, 1)
	defer mm_atomic.AddUint64(&mmInit.afterInitCounter, 1)

	mmInit.t.Helper()

	if mmInit.inspectFuncInit != nil {
		mmInit.inspectFuncInit(streamKey)
	}

	mm_params := YoutubeClientMockInitParams{streamKey}

	// Record call args
	mmInit.InitMock.mutex.Lock()
	mmInit.InitMock.callArgs = append(mmInit.InitMock.callArgs, &mm_params)
	mmInit.InitMock.mutex.Unlock()

	for _, e := range mmInit.InitMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmInit.InitMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInit.InitMock.defaultExpectation.Counter, 1)
		mm_want := mmInit.InitMock.defaultExpectation.params
		mm_want_ptrs := mmInit.InitMock.defaultExpectation.paramPtrs

		mm_got := YoutubeClientMockInitParams{streamKey}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.streamKey != nil && !minimock.Equal(*mm_want_ptrs.streamKey, mm_got.streamKey) {
				mmInit.t.Errorf("YoutubeClientMock.Init got unexpected parameter streamKey, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInit.InitMock.defaultExpectation.expectationOrigins.originStreamKey, *mm_want_ptrs.streamKey, mm_got.streamKey, minimock.Diff(*mm_want_ptrs.streamKey, mm_got.streamKey))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInit.t.Errorf("YoutubeClientMock.Init got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInit.InitMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInit.InitMock.defaultExpectation.results
		if mm_results == nil {
			mmInit.t.Fatal("No results are set for the YoutubeClientMock.Init")
		}
		return (*mm_results).err
	}
	if mmInit.funcInit != nil {
		return mmInit.funcInit(streamKey)
	}
	mmInit.t.Fatalf("Unexpected call to YoutubeClientMock.Init. %v", streamKey)
	return
}

// InitAfterCounter returns a count of finished YoutubeClientMock.Init invocations
func (mmInit *YoutubeClientMock) InitAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInit.afterInitCounter)
}

// InitBeforeCounter returns a count of YoutubeClientMock.Init invocations
func (mmInit *YoutubeClientMock) InitBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInit.beforeInitCounter)
}

// Calls returns a list of arguments used in each call to YoutubeClientMock.Init.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInit *mYoutubeClientMockInit) Calls() []*YoutubeClientMockInitParams {
	mmInit.mutex.RLock()

	argCopy := make([]*YoutubeClientMockInitParams, len(mmInit.callArgs))
	copy(argCopy, mmInit.callArgs)

	mmInit.mutex.RUnlock()

	return argCopy
}

// MinimockInitDone returns true if the count of the Init invocations corresponds
// the number of defined expectations
func (m *YoutubeClientMock) MinimockInitDone() bool {
	if m.InitMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InitMock.invocationsDone()
}

// MinimockInitInspect logs each unmet expectation
func (m *YoutubeClientMock) MinimockInitInspect() {
	for _, e := range m.InitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to YoutubeClientMock.Init at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInitCounter := mm_atomic.LoadUint64(&m.afterInitCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InitMock.defaultExpectation != nil && afterInitCounter < 1 {
		if m.InitMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to YoutubeClientMock.Init at\n%s", m.InitMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to YoutubeClientMock.Init at\n%s with params: %#v", m.InitMock.defaultExpectation.expectationOrigins.origin, *m.InitMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInit != nil && afterInitCounter < 1 {
		m.t.Errorf("Expected call to YoutubeClientMock.Init at\n%s", m.funcInitOrigin)
	}

	if !m.InitMock.invocationsDone() && afterInitCounter > 0 {
		m.t.Errorf("Expected %d calls to YoutubeClientMock.Init at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InitMock.expectedInvocations), m.InitMock.expectedInvocationsOrigin, afterInitCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *YoutubeClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetLastTranslationIDInspect()

			m.MinimockGetMessagesInspect()

			m.MinimockInitInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *YoutubeClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *YoutubeClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetLastTranslationIDDone() &&
		m.MinimockGetMessagesDone() &&
		m.MinimockInitDone()
}
