// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/PlayingPossumHiss/possum_chat/internal/entity"
	"github.com/gojuno/minimock/v3"
)

// TwitchIrcClientMock implements mm_twitch.TwitchIrcClient
type TwitchIrcClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcListen          func(callback func(entity.Message), channelName string) (err error)
	funcListenOrigin    string
	inspectFuncListen   func(callback func(entity.Message), channelName string)
	afterListenCounter  uint64
	beforeListenCounter uint64
	ListenMock          mTwitchIrcClientMockListen
}

// NewTwitchIrcClientMock returns a mock for mm_twitch.TwitchIrcClient
func NewTwitchIrcClientMock(t minimock.Tester) *TwitchIrcClientMock {
	m := &TwitchIrcClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ListenMock = mTwitchIrcClientMockListen{mock: m}
	m.ListenMock.callArgs = []*TwitchIrcClientMockListenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTwitchIrcClientMockListen struct {
	optional           bool
	mock               *TwitchIrcClientMock
	defaultExpectation *TwitchIrcClientMockListenExpectation
	expectations       []*TwitchIrcClientMockListenExpectation

	callArgs []*TwitchIrcClientMockListenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TwitchIrcClientMockListenExpectation specifies expectation struct of the TwitchIrcClient.Listen
type TwitchIrcClientMockListenExpectation struct {
	mock               *TwitchIrcClientMock
	params             *TwitchIrcClientMockListenParams
	paramPtrs          *TwitchIrcClientMockListenParamPtrs
	expectationOrigins TwitchIrcClientMockListenExpectationOrigins
	results            *TwitchIrcClientMockListenResults
	returnOrigin       string
	Counter            uint64
}

// TwitchIrcClientMockListenParams contains parameters of the TwitchIrcClient.Listen
type TwitchIrcClientMockListenParams struct {
	callback    func(entity.Message)
	channelName string
}

// TwitchIrcClientMockListenParamPtrs contains pointers to parameters of the TwitchIrcClient.Listen
type TwitchIrcClientMockListenParamPtrs struct {
	callback    *func(entity.Message)
	channelName *string
}

// TwitchIrcClientMockListenResults contains results of the TwitchIrcClient.Listen
type TwitchIrcClientMockListenResults struct {
	err error
}

// TwitchIrcClientMockListenOrigins contains origins of expectations of the TwitchIrcClient.Listen
type TwitchIrcClientMockListenExpectationOrigins struct {
	origin            string
	originCallback    string
	originChannelName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListen *mTwitchIrcClientMockListen) Optional() *mTwitchIrcClientMockListen {
	mmListen.optional = true
	return mmListen
}

// Expect sets up expected params for TwitchIrcClient.Listen
func (mmListen *mTwitchIrcClientMockListen) Expect(callback func(entity.Message), channelName string) *mTwitchIrcClientMockListen {
	if mmListen.mock.funcListen != nil {
		mmListen.mock.t.Fatalf("TwitchIrcClientMock.Listen mock is already set by Set")
	}

	if mmListen.defaultExpectation == nil {
		mmListen.defaultExpectation = &TwitchIrcClientMockListenExpectation{}
	}

	if mmListen.defaultExpectation.paramPtrs != nil {
		mmListen.mock.t.Fatalf("TwitchIrcClientMock.Listen mock is already set by ExpectParams functions")
	}

	mmListen.defaultExpectation.params = &TwitchIrcClientMockListenParams{callback, channelName}
	mmListen.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListen.expectations {
		if minimock.Equal(e.params, mmListen.defaultExpectation.params) {
			mmListen.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListen.defaultExpectation.params)
		}
	}

	return mmListen
}

// ExpectCallbackParam1 sets up expected param callback for TwitchIrcClient.Listen
func (mmListen *mTwitchIrcClientMockListen) ExpectCallbackParam1(callback func(entity.Message)) *mTwitchIrcClientMockListen {
	if mmListen.mock.funcListen != nil {
		mmListen.mock.t.Fatalf("TwitchIrcClientMock.Listen mock is already set by Set")
	}

	if mmListen.defaultExpectation == nil {
		mmListen.defaultExpectation = &TwitchIrcClientMockListenExpectation{}
	}

	if mmListen.defaultExpectation.params != nil {
		mmListen.mock.t.Fatalf("TwitchIrcClientMock.Listen mock is already set by Expect")
	}

	if mmListen.defaultExpectation.paramPtrs == nil {
		mmListen.defaultExpectation.paramPtrs = &TwitchIrcClientMockListenParamPtrs{}
	}
	mmListen.defaultExpectation.paramPtrs.callback = &callback
	mmListen.defaultExpectation.expectationOrigins.originCallback = minimock.CallerInfo(1)

	return mmListen
}

// ExpectChannelNameParam2 sets up expected param channelName for TwitchIrcClient.Listen
func (mmListen *mTwitchIrcClientMockListen) ExpectChannelNameParam2(channelName string) *mTwitchIrcClientMockListen {
	if mmListen.mock.funcListen != nil {
		mmListen.mock.t.Fatalf("TwitchIrcClientMock.Listen mock is already set by Set")
	}

	if mmListen.defaultExpectation == nil {
		mmListen.defaultExpectation = &TwitchIrcClientMockListenExpectation{}
	}

	if mmListen.defaultExpectation.params != nil {
		mmListen.mock.t.Fatalf("TwitchIrcClientMock.Listen mock is already set by Expect")
	}

	if mmListen.defaultExpectation.paramPtrs == nil {
		mmListen.defaultExpectation.paramPtrs = &TwitchIrcClientMockListenParamPtrs{}
	}
	mmListen.defaultExpectation.paramPtrs.channelName = &channelName
	mmListen.defaultExpectation.expectationOrigins.originChannelName = minimock.CallerInfo(1)

	return mmListen
}

// Inspect accepts an inspector function that has same arguments as the TwitchIrcClient.Listen
func (mmListen *mTwitchIrcClientMockListen) Inspect(f func(callback func(entity.Message), channelName string)) *mTwitchIrcClientMockListen {
	if mmListen.mock.inspectFuncListen != nil {
		mmListen.mock.t.Fatalf("Inspect function is already set for TwitchIrcClientMock.Listen")
	}

	mmListen.mock.inspectFuncListen = f

	return mmListen
}

// Return sets up results that will be returned by TwitchIrcClient.Listen
func (mmListen *mTwitchIrcClientMockListen) Return(err error) *TwitchIrcClientMock {
	if mmListen.mock.funcListen != nil {
		mmListen.mock.t.Fatalf("TwitchIrcClientMock.Listen mock is already set by Set")
	}

	if mmListen.defaultExpectation == nil {
		mmListen.defaultExpectation = &TwitchIrcClientMockListenExpectation{mock: mmListen.mock}
	}
	mmListen.defaultExpectation.results = &TwitchIrcClientMockListenResults{err}
	mmListen.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListen.mock
}

// Set uses given function f to mock the TwitchIrcClient.Listen method
func (mmListen *mTwitchIrcClientMockListen) Set(f func(callback func(entity.Message), channelName string) (err error)) *TwitchIrcClientMock {
	if mmListen.defaultExpectation != nil {
		mmListen.mock.t.Fatalf("Default expectation is already set for the TwitchIrcClient.Listen method")
	}

	if len(mmListen.expectations) > 0 {
		mmListen.mock.t.Fatalf("Some expectations are already set for the TwitchIrcClient.Listen method")
	}

	mmListen.mock.funcListen = f
	mmListen.mock.funcListenOrigin = minimock.CallerInfo(1)
	return mmListen.mock
}

// When sets expectation for the TwitchIrcClient.Listen which will trigger the result defined by the following
// Then helper
func (mmListen *mTwitchIrcClientMockListen) When(callback func(entity.Message), channelName string) *TwitchIrcClientMockListenExpectation {
	if mmListen.mock.funcListen != nil {
		mmListen.mock.t.Fatalf("TwitchIrcClientMock.Listen mock is already set by Set")
	}

	expectation := &TwitchIrcClientMockListenExpectation{
		mock:               mmListen.mock,
		params:             &TwitchIrcClientMockListenParams{callback, channelName},
		expectationOrigins: TwitchIrcClientMockListenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListen.expectations = append(mmListen.expectations, expectation)
	return expectation
}

// Then sets up TwitchIrcClient.Listen return parameters for the expectation previously defined by the When method
func (e *TwitchIrcClientMockListenExpectation) Then(err error) *TwitchIrcClientMock {
	e.results = &TwitchIrcClientMockListenResults{err}
	return e.mock
}

// Times sets number of times TwitchIrcClient.Listen should be invoked
func (mmListen *mTwitchIrcClientMockListen) Times(n uint64) *mTwitchIrcClientMockListen {
	if n == 0 {
		mmListen.mock.t.Fatalf("Times of TwitchIrcClientMock.Listen mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListen.expectedInvocations, n)
	mmListen.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListen
}

func (mmListen *mTwitchIrcClientMockListen) invocationsDone() bool {
	if len(mmListen.expectations) == 0 && mmListen.defaultExpectation == nil && mmListen.mock.funcListen == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListen.mock.afterListenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListen.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Listen implements mm_twitch.TwitchIrcClient
func (mmListen *TwitchIrcClientMock) Listen(callback func(entity.Message), channelName string) (err error) {
	mm_atomic.AddUint64(&mmListen.beforeListenCounter, 1)
	defer mm_atomic.AddUint64(&mmListen.afterListenCounter, 1)

	mmListen.t.Helper()

	if mmListen.inspectFuncListen != nil {
		mmListen.inspectFuncListen(callback, channelName)
	}

	mm_params := TwitchIrcClientMockListenParams{callback, channelName}

	// Record call args
	mmListen.ListenMock.mutex.Lock()
	mmListen.ListenMock.callArgs = append(mmListen.ListenMock.callArgs, &mm_params)
	mmListen.ListenMock.mutex.Unlock()

	for _, e := range mmListen.ListenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmListen.ListenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListen.ListenMock.defaultExpectation.Counter, 1)
		mm_want := mmListen.ListenMock.defaultExpectation.params
		mm_want_ptrs := mmListen.ListenMock.defaultExpectation.paramPtrs

		mm_got := TwitchIrcClientMockListenParams{callback, channelName}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.callback != nil && !minimock.Equal(*mm_want_ptrs.callback, mm_got.callback) {
				mmListen.t.Errorf("TwitchIrcClientMock.Listen got unexpected parameter callback, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListen.ListenMock.defaultExpectation.expectationOrigins.originCallback, *mm_want_ptrs.callback, mm_got.callback, minimock.Diff(*mm_want_ptrs.callback, mm_got.callback))
			}

			if mm_want_ptrs.channelName != nil && !minimock.Equal(*mm_want_ptrs.channelName, mm_got.channelName) {
				mmListen.t.Errorf("TwitchIrcClientMock.Listen got unexpected parameter channelName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListen.ListenMock.defaultExpectation.expectationOrigins.originChannelName, *mm_want_ptrs.channelName, mm_got.channelName, minimock.Diff(*mm_want_ptrs.channelName, mm_got.channelName))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListen.t.Errorf("TwitchIrcClientMock.Listen got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListen.ListenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListen.ListenMock.defaultExpectation.results
		if mm_results == nil {
			mmListen.t.Fatal("No results are set for the TwitchIrcClientMock.Listen")
		}
		return (*mm_results).err
	}
	if mmListen.funcListen != nil {
		return mmListen.funcListen(callback, channelName)
	}
	mmListen.t.Fatalf("Unexpected call to TwitchIrcClientMock.Listen. %v %v", callback, channelName)
	return
}

// ListenAfterCounter returns a count of finished TwitchIrcClientMock.Listen invocations
func (mmListen *TwitchIrcClientMock) ListenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListen.afterListenCounter)
}

// ListenBeforeCounter returns a count of TwitchIrcClientMock.Listen invocations
func (mmListen *TwitchIrcClientMock) ListenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListen.beforeListenCounter)
}

// Calls returns a list of arguments used in each call to TwitchIrcClientMock.Listen.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListen *mTwitchIrcClientMockListen) Calls() []*TwitchIrcClientMockListenParams {
	mmListen.mutex.RLock()

	argCopy := make([]*TwitchIrcClientMockListenParams, len(mmListen.callArgs))
	copy(argCopy, mmListen.callArgs)

	mmListen.mutex.RUnlock()

	return argCopy
}

// MinimockListenDone returns true if the count of the Listen invocations corresponds
// the number of defined expectations
func (m *TwitchIrcClientMock) MinimockListenDone() bool {
	if m.ListenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListenMock.invocationsDone()
}

// MinimockListenInspect logs each unmet expectation
func (m *TwitchIrcClientMock) MinimockListenInspect() {
	for _, e := range m.ListenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TwitchIrcClientMock.Listen at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListenCounter := mm_atomic.LoadUint64(&m.afterListenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListenMock.defaultExpectation != nil && afterListenCounter < 1 {
		if m.ListenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TwitchIrcClientMock.Listen at\n%s", m.ListenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TwitchIrcClientMock.Listen at\n%s with params: %#v", m.ListenMock.defaultExpectation.expectationOrigins.origin, *m.ListenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListen != nil && afterListenCounter < 1 {
		m.t.Errorf("Expected call to TwitchIrcClientMock.Listen at\n%s", m.funcListenOrigin)
	}

	if !m.ListenMock.invocationsDone() && afterListenCounter > 0 {
		m.t.Errorf("Expected %d calls to TwitchIrcClientMock.Listen at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListenMock.expectedInvocations), m.ListenMock.expectedInvocationsOrigin, afterListenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TwitchIrcClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockListenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TwitchIrcClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TwitchIrcClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockListenDone()
}
