// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/PlayingPossumHiss/possum_chat/internal/entity"
	"github.com/gojuno/minimock/v3"
)

// VkPlayLiveWsMock implements mm_vk_play_live.VkPlayLiveWs
type VkPlayLiveWsMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcClose          func()
	funcCloseOrigin    string
	inspectFuncClose   func()
	afterCloseCounter  uint64
	beforeCloseCounter uint64
	CloseMock          mVkPlayLiveWsMockClose

	funcInit          func(ctx context.Context, token string, userID string) (err error)
	funcInitOrigin    string
	inspectFuncInit   func(ctx context.Context, token string, userID string)
	afterInitCounter  uint64
	beforeInitCounter uint64
	InitMock          mVkPlayLiveWsMockInit

	funcReadMessage          func() (m1 entity.Message, err error)
	funcReadMessageOrigin    string
	inspectFuncReadMessage   func()
	afterReadMessageCounter  uint64
	beforeReadMessageCounter uint64
	ReadMessageMock          mVkPlayLiveWsMockReadMessage

	funcWritePong          func() (err error)
	funcWritePongOrigin    string
	inspectFuncWritePong   func()
	afterWritePongCounter  uint64
	beforeWritePongCounter uint64
	WritePongMock          mVkPlayLiveWsMockWritePong
}

// NewVkPlayLiveWsMock returns a mock for mm_vk_play_live.VkPlayLiveWs
func NewVkPlayLiveWsMock(t minimock.Tester) *VkPlayLiveWsMock {
	m := &VkPlayLiveWsMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CloseMock = mVkPlayLiveWsMockClose{mock: m}

	m.InitMock = mVkPlayLiveWsMockInit{mock: m}
	m.InitMock.callArgs = []*VkPlayLiveWsMockInitParams{}

	m.ReadMessageMock = mVkPlayLiveWsMockReadMessage{mock: m}

	m.WritePongMock = mVkPlayLiveWsMockWritePong{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mVkPlayLiveWsMockClose struct {
	optional           bool
	mock               *VkPlayLiveWsMock
	defaultExpectation *VkPlayLiveWsMockCloseExpectation
	expectations       []*VkPlayLiveWsMockCloseExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VkPlayLiveWsMockCloseExpectation specifies expectation struct of the VkPlayLiveWs.Close
type VkPlayLiveWsMockCloseExpectation struct {
	mock *VkPlayLiveWsMock

	returnOrigin string
	Counter      uint64
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmClose *mVkPlayLiveWsMockClose) Optional() *mVkPlayLiveWsMockClose {
	mmClose.optional = true
	return mmClose
}

// Expect sets up expected params for VkPlayLiveWs.Close
func (mmClose *mVkPlayLiveWsMockClose) Expect() *mVkPlayLiveWsMockClose {
	if mmClose.mock.funcClose != nil {
		mmClose.mock.t.Fatalf("VkPlayLiveWsMock.Close mock is already set by Set")
	}

	if mmClose.defaultExpectation == nil {
		mmClose.defaultExpectation = &VkPlayLiveWsMockCloseExpectation{}
	}

	return mmClose
}

// Inspect accepts an inspector function that has same arguments as the VkPlayLiveWs.Close
func (mmClose *mVkPlayLiveWsMockClose) Inspect(f func()) *mVkPlayLiveWsMockClose {
	if mmClose.mock.inspectFuncClose != nil {
		mmClose.mock.t.Fatalf("Inspect function is already set for VkPlayLiveWsMock.Close")
	}

	mmClose.mock.inspectFuncClose = f

	return mmClose
}

// Return sets up results that will be returned by VkPlayLiveWs.Close
func (mmClose *mVkPlayLiveWsMockClose) Return() *VkPlayLiveWsMock {
	if mmClose.mock.funcClose != nil {
		mmClose.mock.t.Fatalf("VkPlayLiveWsMock.Close mock is already set by Set")
	}

	if mmClose.defaultExpectation == nil {
		mmClose.defaultExpectation = &VkPlayLiveWsMockCloseExpectation{mock: mmClose.mock}
	}

	mmClose.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmClose.mock
}

// Set uses given function f to mock the VkPlayLiveWs.Close method
func (mmClose *mVkPlayLiveWsMockClose) Set(f func()) *VkPlayLiveWsMock {
	if mmClose.defaultExpectation != nil {
		mmClose.mock.t.Fatalf("Default expectation is already set for the VkPlayLiveWs.Close method")
	}

	if len(mmClose.expectations) > 0 {
		mmClose.mock.t.Fatalf("Some expectations are already set for the VkPlayLiveWs.Close method")
	}

	mmClose.mock.funcClose = f
	mmClose.mock.funcCloseOrigin = minimock.CallerInfo(1)
	return mmClose.mock
}

// Times sets number of times VkPlayLiveWs.Close should be invoked
func (mmClose *mVkPlayLiveWsMockClose) Times(n uint64) *mVkPlayLiveWsMockClose {
	if n == 0 {
		mmClose.mock.t.Fatalf("Times of VkPlayLiveWsMock.Close mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmClose.expectedInvocations, n)
	mmClose.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmClose
}

func (mmClose *mVkPlayLiveWsMockClose) invocationsDone() bool {
	if len(mmClose.expectations) == 0 && mmClose.defaultExpectation == nil && mmClose.mock.funcClose == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmClose.mock.afterCloseCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmClose.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Close implements mm_vk_play_live.VkPlayLiveWs
func (mmClose *VkPlayLiveWsMock) Close() {
	mm_atomic.AddUint64(&mmClose.beforeCloseCounter, 1)
	defer mm_atomic.AddUint64(&mmClose.afterCloseCounter, 1)

	mmClose.t.Helper()

	if mmClose.inspectFuncClose != nil {
		mmClose.inspectFuncClose()
	}

	if mmClose.CloseMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmClose.CloseMock.defaultExpectation.Counter, 1)

		return

	}
	if mmClose.funcClose != nil {
		mmClose.funcClose()
		return
	}
	mmClose.t.Fatalf("Unexpected call to VkPlayLiveWsMock.Close.")

}

// CloseAfterCounter returns a count of finished VkPlayLiveWsMock.Close invocations
func (mmClose *VkPlayLiveWsMock) CloseAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmClose.afterCloseCounter)
}

// CloseBeforeCounter returns a count of VkPlayLiveWsMock.Close invocations
func (mmClose *VkPlayLiveWsMock) CloseBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmClose.beforeCloseCounter)
}

// MinimockCloseDone returns true if the count of the Close invocations corresponds
// the number of defined expectations
func (m *VkPlayLiveWsMock) MinimockCloseDone() bool {
	if m.CloseMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CloseMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CloseMock.invocationsDone()
}

// MinimockCloseInspect logs each unmet expectation
func (m *VkPlayLiveWsMock) MinimockCloseInspect() {
	for _, e := range m.CloseMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to VkPlayLiveWsMock.Close")
		}
	}

	afterCloseCounter := mm_atomic.LoadUint64(&m.afterCloseCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CloseMock.defaultExpectation != nil && afterCloseCounter < 1 {
		m.t.Errorf("Expected call to VkPlayLiveWsMock.Close at\n%s", m.CloseMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcClose != nil && afterCloseCounter < 1 {
		m.t.Errorf("Expected call to VkPlayLiveWsMock.Close at\n%s", m.funcCloseOrigin)
	}

	if !m.CloseMock.invocationsDone() && afterCloseCounter > 0 {
		m.t.Errorf("Expected %d calls to VkPlayLiveWsMock.Close at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CloseMock.expectedInvocations), m.CloseMock.expectedInvocationsOrigin, afterCloseCounter)
	}
}

type mVkPlayLiveWsMockInit struct {
	optional           bool
	mock               *VkPlayLiveWsMock
	defaultExpectation *VkPlayLiveWsMockInitExpectation
	expectations       []*VkPlayLiveWsMockInitExpectation

	callArgs []*VkPlayLiveWsMockInitParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VkPlayLiveWsMockInitExpectation specifies expectation struct of the VkPlayLiveWs.Init
type VkPlayLiveWsMockInitExpectation struct {
	mock               *VkPlayLiveWsMock
	params             *VkPlayLiveWsMockInitParams
	paramPtrs          *VkPlayLiveWsMockInitParamPtrs
	expectationOrigins VkPlayLiveWsMockInitExpectationOrigins
	results            *VkPlayLiveWsMockInitResults
	returnOrigin       string
	Counter            uint64
}

// VkPlayLiveWsMockInitParams contains parameters of the VkPlayLiveWs.Init
type VkPlayLiveWsMockInitParams struct {
	ctx    context.Context
	token  string
	userID string
}

// VkPlayLiveWsMockInitParamPtrs contains pointers to parameters of the VkPlayLiveWs.Init
type VkPlayLiveWsMockInitParamPtrs struct {
	ctx    *context.Context
	token  *string
	userID *string
}

// VkPlayLiveWsMockInitResults contains results of the VkPlayLiveWs.Init
type VkPlayLiveWsMockInitResults struct {
	err error
}

// VkPlayLiveWsMockInitOrigins contains origins of expectations of the VkPlayLiveWs.Init
type VkPlayLiveWsMockInitExpectationOrigins struct {
	origin       string
	originCtx    string
	originToken  string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInit *mVkPlayLiveWsMockInit) Optional() *mVkPlayLiveWsMockInit {
	mmInit.optional = true
	return mmInit
}

// Expect sets up expected params for VkPlayLiveWs.Init
func (mmInit *mVkPlayLiveWsMockInit) Expect(ctx context.Context, token string, userID string) *mVkPlayLiveWsMockInit {
	if mmInit.mock.funcInit != nil {
		mmInit.mock.t.Fatalf("VkPlayLiveWsMock.Init mock is already set by Set")
	}

	if mmInit.defaultExpectation == nil {
		mmInit.defaultExpectation = &VkPlayLiveWsMockInitExpectation{}
	}

	if mmInit.defaultExpectation.paramPtrs != nil {
		mmInit.mock.t.Fatalf("VkPlayLiveWsMock.Init mock is already set by ExpectParams functions")
	}

	mmInit.defaultExpectation.params = &VkPlayLiveWsMockInitParams{ctx, token, userID}
	mmInit.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInit.expectations {
		if minimock.Equal(e.params, mmInit.defaultExpectation.params) {
			mmInit.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInit.defaultExpectation.params)
		}
	}

	return mmInit
}

// ExpectCtxParam1 sets up expected param ctx for VkPlayLiveWs.Init
func (mmInit *mVkPlayLiveWsMockInit) ExpectCtxParam1(ctx context.Context) *mVkPlayLiveWsMockInit {
	if mmInit.mock.funcInit != nil {
		mmInit.mock.t.Fatalf("VkPlayLiveWsMock.Init mock is already set by Set")
	}

	if mmInit.defaultExpectation == nil {
		mmInit.defaultExpectation = &VkPlayLiveWsMockInitExpectation{}
	}

	if mmInit.defaultExpectation.params != nil {
		mmInit.mock.t.Fatalf("VkPlayLiveWsMock.Init mock is already set by Expect")
	}

	if mmInit.defaultExpectation.paramPtrs == nil {
		mmInit.defaultExpectation.paramPtrs = &VkPlayLiveWsMockInitParamPtrs{}
	}
	mmInit.defaultExpectation.paramPtrs.ctx = &ctx
	mmInit.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmInit
}

// ExpectTokenParam2 sets up expected param token for VkPlayLiveWs.Init
func (mmInit *mVkPlayLiveWsMockInit) ExpectTokenParam2(token string) *mVkPlayLiveWsMockInit {
	if mmInit.mock.funcInit != nil {
		mmInit.mock.t.Fatalf("VkPlayLiveWsMock.Init mock is already set by Set")
	}

	if mmInit.defaultExpectation == nil {
		mmInit.defaultExpectation = &VkPlayLiveWsMockInitExpectation{}
	}

	if mmInit.defaultExpectation.params != nil {
		mmInit.mock.t.Fatalf("VkPlayLiveWsMock.Init mock is already set by Expect")
	}

	if mmInit.defaultExpectation.paramPtrs == nil {
		mmInit.defaultExpectation.paramPtrs = &VkPlayLiveWsMockInitParamPtrs{}
	}
	mmInit.defaultExpectation.paramPtrs.token = &token
	mmInit.defaultExpectation.expectationOrigins.originToken = minimock.CallerInfo(1)

	return mmInit
}

// ExpectUserIDParam3 sets up expected param userID for VkPlayLiveWs.Init
func (mmInit *mVkPlayLiveWsMockInit) ExpectUserIDParam3(userID string) *mVkPlayLiveWsMockInit {
	if mmInit.mock.funcInit != nil {
		mmInit.mock.t.Fatalf("VkPlayLiveWsMock.Init mock is already set by Set")
	}

	if mmInit.defaultExpectation == nil {
		mmInit.defaultExpectation = &VkPlayLiveWsMockInitExpectation{}
	}

	if mmInit.defaultExpectation.params != nil {
		mmInit.mock.t.Fatalf("VkPlayLiveWsMock.Init mock is already set by Expect")
	}

	if mmInit.defaultExpectation.paramPtrs == nil {
		mmInit.defaultExpectation.paramPtrs = &VkPlayLiveWsMockInitParamPtrs{}
	}
	mmInit.defaultExpectation.paramPtrs.userID = &userID
	mmInit.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmInit
}

// Inspect accepts an inspector function that has same arguments as the VkPlayLiveWs.Init
func (mmInit *mVkPlayLiveWsMockInit) Inspect(f func(ctx context.Context, token string, userID string)) *mVkPlayLiveWsMockInit {
	if mmInit.mock.inspectFuncInit != nil {
		mmInit.mock.t.Fatalf("Inspect function is already set for VkPlayLiveWsMock.Init")
	}

	mmInit.mock.inspectFuncInit = f

	return mmInit
}

// Return sets up results that will be returned by VkPlayLiveWs.Init
func (mmInit *mVkPlayLiveWsMockInit) Return(err error) *VkPlayLiveWsMock {
	if mmInit.mock.funcInit != nil {
		mmInit.mock.t.Fatalf("VkPlayLiveWsMock.Init mock is already set by Set")
	}

	if mmInit.defaultExpectation == nil {
		mmInit.defaultExpectation = &VkPlayLiveWsMockInitExpectation{mock: mmInit.mock}
	}
	mmInit.defaultExpectation.results = &VkPlayLiveWsMockInitResults{err}
	mmInit.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInit.mock
}

// Set uses given function f to mock the VkPlayLiveWs.Init method
func (mmInit *mVkPlayLiveWsMockInit) Set(f func(ctx context.Context, token string, userID string) (err error)) *VkPlayLiveWsMock {
	if mmInit.defaultExpectation != nil {
		mmInit.mock.t.Fatalf("Default expectation is already set for the VkPlayLiveWs.Init method")
	}

	if len(mmInit.expectations) > 0 {
		mmInit.mock.t.Fatalf("Some expectations are already set for the VkPlayLiveWs.Init method")
	}

	mmInit.mock.funcInit = f
	mmInit.mock.funcInitOrigin = minimock.CallerInfo(1)
	return mmInit.mock
}

// When sets expectation for the VkPlayLiveWs.Init which will trigger the result defined by the following
// Then helper
func (mmInit *mVkPlayLiveWsMockInit) When(ctx context.Context, token string, userID string) *VkPlayLiveWsMockInitExpectation {
	if mmInit.mock.funcInit != nil {
		mmInit.mock.t.Fatalf("VkPlayLiveWsMock.Init mock is already set by Set")
	}

	expectation := &VkPlayLiveWsMockInitExpectation{
		mock:               mmInit.mock,
		params:             &VkPlayLiveWsMockInitParams{ctx, token, userID},
		expectationOrigins: VkPlayLiveWsMockInitExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInit.expectations = append(mmInit.expectations, expectation)
	return expectation
}

// Then sets up VkPlayLiveWs.Init return parameters for the expectation previously defined by the When method
func (e *VkPlayLiveWsMockInitExpectation) Then(err error) *VkPlayLiveWsMock {
	e.results = &VkPlayLiveWsMockInitResults{err}
	return e.mock
}

// Times sets number of times VkPlayLiveWs.Init should be invoked
func (mmInit *mVkPlayLiveWsMockInit) Times(n uint64) *mVkPlayLiveWsMockInit {
	if n == 0 {
		mmInit.mock.t.Fatalf("Times of VkPlayLiveWsMock.Init mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInit.expectedInvocations, n)
	mmInit.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInit
}

func (mmInit *mVkPlayLiveWsMockInit) invocationsDone() bool {
	if len(mmInit.expectations) == 0 && mmInit.defaultExpectation == nil && mmInit.mock.funcInit == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInit.mock.afterInitCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInit.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Init implements mm_vk_play_live.VkPlayLiveWs
func (mmInit *VkPlayLiveWsMock) Init(ctx context.Context, token string, userID string) (err error) {
	mm_atomic.AddUint64(&mmInit.beforeInitCounter, 1)
	defer mm_atomic.AddUint64(&mmInit.afterInitCounter, 1)

	mmInit.t.Helper()

	if mmInit.inspectFuncInit != nil {
		mmInit.inspectFuncInit(ctx, token, userID)
	}

	mm_params := VkPlayLiveWsMockInitParams{ctx, token, userID}

	// Record call args
	mmInit.InitMock.mutex.Lock()
	mmInit.InitMock.callArgs = append(mmInit.InitMock.callArgs, &mm_params)
	mmInit.InitMock.mutex.Unlock()

	for _, e := range mmInit.InitMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmInit.InitMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInit.InitMock.defaultExpectation.Counter, 1)
		mm_want := mmInit.InitMock.defaultExpectation.params
		mm_want_ptrs := mmInit.InitMock.defaultExpectation.paramPtrs

		mm_got := VkPlayLiveWsMockInitParams{ctx, token, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmInit.t.Errorf("VkPlayLiveWsMock.Init got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInit.InitMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.token != nil && !minimock.Equal(*mm_want_ptrs.token, mm_got.token) {
				mmInit.t.Errorf("VkPlayLiveWsMock.Init got unexpected parameter token, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInit.InitMock.defaultExpectation.expectationOrigins.originToken, *mm_want_ptrs.token, mm_got.token, minimock.Diff(*mm_want_ptrs.token, mm_got.token))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmInit.t.Errorf("VkPlayLiveWsMock.Init got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInit.InitMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInit.t.Errorf("VkPlayLiveWsMock.Init got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInit.InitMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInit.InitMock.defaultExpectation.results
		if mm_results == nil {
			mmInit.t.Fatal("No results are set for the VkPlayLiveWsMock.Init")
		}
		return (*mm_results).err
	}
	if mmInit.funcInit != nil {
		return mmInit.funcInit(ctx, token, userID)
	}
	mmInit.t.Fatalf("Unexpected call to VkPlayLiveWsMock.Init. %v %v %v", ctx, token, userID)
	return
}

// InitAfterCounter returns a count of finished VkPlayLiveWsMock.Init invocations
func (mmInit *VkPlayLiveWsMock) InitAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInit.afterInitCounter)
}

// InitBeforeCounter returns a count of VkPlayLiveWsMock.Init invocations
func (mmInit *VkPlayLiveWsMock) InitBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInit.beforeInitCounter)
}

// Calls returns a list of arguments used in each call to VkPlayLiveWsMock.Init.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInit *mVkPlayLiveWsMockInit) Calls() []*VkPlayLiveWsMockInitParams {
	mmInit.mutex.RLock()

	argCopy := make([]*VkPlayLiveWsMockInitParams, len(mmInit.callArgs))
	copy(argCopy, mmInit.callArgs)

	mmInit.mutex.RUnlock()

	return argCopy
}

// MinimockInitDone returns true if the count of the Init invocations corresponds
// the number of defined expectations
func (m *VkPlayLiveWsMock) MinimockInitDone() bool {
	if m.InitMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InitMock.invocationsDone()
}

// MinimockInitInspect logs each unmet expectation
func (m *VkPlayLiveWsMock) MinimockInitInspect() {
	for _, e := range m.InitMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to VkPlayLiveWsMock.Init at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInitCounter := mm_atomic.LoadUint64(&m.afterInitCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InitMock.defaultExpectation != nil && afterInitCounter < 1 {
		if m.InitMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to VkPlayLiveWsMock.Init at\n%s", m.InitMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to VkPlayLiveWsMock.Init at\n%s with params: %#v", m.InitMock.defaultExpectation.expectationOrigins.origin, *m.InitMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInit != nil && afterInitCounter < 1 {
		m.t.Errorf("Expected call to VkPlayLiveWsMock.Init at\n%s", m.funcInitOrigin)
	}

	if !m.InitMock.invocationsDone() && afterInitCounter > 0 {
		m.t.Errorf("Expected %d calls to VkPlayLiveWsMock.Init at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InitMock.expectedInvocations), m.InitMock.expectedInvocationsOrigin, afterInitCounter)
	}
}

type mVkPlayLiveWsMockReadMessage struct {
	optional           bool
	mock               *VkPlayLiveWsMock
	defaultExpectation *VkPlayLiveWsMockReadMessageExpectation
	expectations       []*VkPlayLiveWsMockReadMessageExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VkPlayLiveWsMockReadMessageExpectation specifies expectation struct of the VkPlayLiveWs.ReadMessage
type VkPlayLiveWsMockReadMessageExpectation struct {
	mock *VkPlayLiveWsMock

	results      *VkPlayLiveWsMockReadMessageResults
	returnOrigin string
	Counter      uint64
}

// VkPlayLiveWsMockReadMessageResults contains results of the VkPlayLiveWs.ReadMessage
type VkPlayLiveWsMockReadMessageResults struct {
	m1  entity.Message
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmReadMessage *mVkPlayLiveWsMockReadMessage) Optional() *mVkPlayLiveWsMockReadMessage {
	mmReadMessage.optional = true
	return mmReadMessage
}

// Expect sets up expected params for VkPlayLiveWs.ReadMessage
func (mmReadMessage *mVkPlayLiveWsMockReadMessage) Expect() *mVkPlayLiveWsMockReadMessage {
	if mmReadMessage.mock.funcReadMessage != nil {
		mmReadMessage.mock.t.Fatalf("VkPlayLiveWsMock.ReadMessage mock is already set by Set")
	}

	if mmReadMessage.defaultExpectation == nil {
		mmReadMessage.defaultExpectation = &VkPlayLiveWsMockReadMessageExpectation{}
	}

	return mmReadMessage
}

// Inspect accepts an inspector function that has same arguments as the VkPlayLiveWs.ReadMessage
func (mmReadMessage *mVkPlayLiveWsMockReadMessage) Inspect(f func()) *mVkPlayLiveWsMockReadMessage {
	if mmReadMessage.mock.inspectFuncReadMessage != nil {
		mmReadMessage.mock.t.Fatalf("Inspect function is already set for VkPlayLiveWsMock.ReadMessage")
	}

	mmReadMessage.mock.inspectFuncReadMessage = f

	return mmReadMessage
}

// Return sets up results that will be returned by VkPlayLiveWs.ReadMessage
func (mmReadMessage *mVkPlayLiveWsMockReadMessage) Return(m1 entity.Message, err error) *VkPlayLiveWsMock {
	if mmReadMessage.mock.funcReadMessage != nil {
		mmReadMessage.mock.t.Fatalf("VkPlayLiveWsMock.ReadMessage mock is already set by Set")
	}

	if mmReadMessage.defaultExpectation == nil {
		mmReadMessage.defaultExpectation = &VkPlayLiveWsMockReadMessageExpectation{mock: mmReadMessage.mock}
	}
	mmReadMessage.defaultExpectation.results = &VkPlayLiveWsMockReadMessageResults{m1, err}
	mmReadMessage.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmReadMessage.mock
}

// Set uses given function f to mock the VkPlayLiveWs.ReadMessage method
func (mmReadMessage *mVkPlayLiveWsMockReadMessage) Set(f func() (m1 entity.Message, err error)) *VkPlayLiveWsMock {
	if mmReadMessage.defaultExpectation != nil {
		mmReadMessage.mock.t.Fatalf("Default expectation is already set for the VkPlayLiveWs.ReadMessage method")
	}

	if len(mmReadMessage.expectations) > 0 {
		mmReadMessage.mock.t.Fatalf("Some expectations are already set for the VkPlayLiveWs.ReadMessage method")
	}

	mmReadMessage.mock.funcReadMessage = f
	mmReadMessage.mock.funcReadMessageOrigin = minimock.CallerInfo(1)
	return mmReadMessage.mock
}

// Times sets number of times VkPlayLiveWs.ReadMessage should be invoked
func (mmReadMessage *mVkPlayLiveWsMockReadMessage) Times(n uint64) *mVkPlayLiveWsMockReadMessage {
	if n == 0 {
		mmReadMessage.mock.t.Fatalf("Times of VkPlayLiveWsMock.ReadMessage mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmReadMessage.expectedInvocations, n)
	mmReadMessage.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmReadMessage
}

func (mmReadMessage *mVkPlayLiveWsMockReadMessage) invocationsDone() bool {
	if len(mmReadMessage.expectations) == 0 && mmReadMessage.defaultExpectation == nil && mmReadMessage.mock.funcReadMessage == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmReadMessage.mock.afterReadMessageCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmReadMessage.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ReadMessage implements mm_vk_play_live.VkPlayLiveWs
func (mmReadMessage *VkPlayLiveWsMock) ReadMessage() (m1 entity.Message, err error) {
	mm_atomic.AddUint64(&mmReadMessage.beforeReadMessageCounter, 1)
	defer mm_atomic.AddUint64(&mmReadMessage.afterReadMessageCounter, 1)

	mmReadMessage.t.Helper()

	if mmReadMessage.inspectFuncReadMessage != nil {
		mmReadMessage.inspectFuncReadMessage()
	}

	if mmReadMessage.ReadMessageMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmReadMessage.ReadMessageMock.defaultExpectation.Counter, 1)

		mm_results := mmReadMessage.ReadMessageMock.defaultExpectation.results
		if mm_results == nil {
			mmReadMessage.t.Fatal("No results are set for the VkPlayLiveWsMock.ReadMessage")
		}
		return (*mm_results).m1, (*mm_results).err
	}
	if mmReadMessage.funcReadMessage != nil {
		return mmReadMessage.funcReadMessage()
	}
	mmReadMessage.t.Fatalf("Unexpected call to VkPlayLiveWsMock.ReadMessage.")
	return
}

// ReadMessageAfterCounter returns a count of finished VkPlayLiveWsMock.ReadMessage invocations
func (mmReadMessage *VkPlayLiveWsMock) ReadMessageAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReadMessage.afterReadMessageCounter)
}

// ReadMessageBeforeCounter returns a count of VkPlayLiveWsMock.ReadMessage invocations
func (mmReadMessage *VkPlayLiveWsMock) ReadMessageBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReadMessage.beforeReadMessageCounter)
}

// MinimockReadMessageDone returns true if the count of the ReadMessage invocations corresponds
// the number of defined expectations
func (m *VkPlayLiveWsMock) MinimockReadMessageDone() bool {
	if m.ReadMessageMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ReadMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ReadMessageMock.invocationsDone()
}

// MinimockReadMessageInspect logs each unmet expectation
func (m *VkPlayLiveWsMock) MinimockReadMessageInspect() {
	for _, e := range m.ReadMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to VkPlayLiveWsMock.ReadMessage")
		}
	}

	afterReadMessageCounter := mm_atomic.LoadUint64(&m.afterReadMessageCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ReadMessageMock.defaultExpectation != nil && afterReadMessageCounter < 1 {
		m.t.Errorf("Expected call to VkPlayLiveWsMock.ReadMessage at\n%s", m.ReadMessageMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReadMessage != nil && afterReadMessageCounter < 1 {
		m.t.Errorf("Expected call to VkPlayLiveWsMock.ReadMessage at\n%s", m.funcReadMessageOrigin)
	}

	if !m.ReadMessageMock.invocationsDone() && afterReadMessageCounter > 0 {
		m.t.Errorf("Expected %d calls to VkPlayLiveWsMock.ReadMessage at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ReadMessageMock.expectedInvocations), m.ReadMessageMock.expectedInvocationsOrigin, afterReadMessageCounter)
	}
}

type mVkPlayLiveWsMockWritePong struct {
	optional           bool
	mock               *VkPlayLiveWsMock
	defaultExpectation *VkPlayLiveWsMockWritePongExpectation
	expectations       []*VkPlayLiveWsMockWritePongExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VkPlayLiveWsMockWritePongExpectation specifies expectation struct of the VkPlayLiveWs.WritePong
type VkPlayLiveWsMockWritePongExpectation struct {
	mock *VkPlayLiveWsMock

	results      *VkPlayLiveWsMockWritePongResults
	returnOrigin string
	Counter      uint64
}

// VkPlayLiveWsMockWritePongResults contains results of the VkPlayLiveWs.WritePong
type VkPlayLiveWsMockWritePongResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmWritePong *mVkPlayLiveWsMockWritePong) Optional() *mVkPlayLiveWsMockWritePong {
	mmWritePong.optional = true
	return mmWritePong
}

// Expect sets up expected params for VkPlayLiveWs.WritePong
func (mmWritePong *mVkPlayLiveWsMockWritePong) Expect() *mVkPlayLiveWsMockWritePong {
	if mmWritePong.mock.funcWritePong != nil {
		mmWritePong.mock.t.Fatalf("VkPlayLiveWsMock.WritePong mock is already set by Set")
	}

	if mmWritePong.defaultExpectation == nil {
		mmWritePong.defaultExpectation = &VkPlayLiveWsMockWritePongExpectation{}
	}

	return mmWritePong
}

// Inspect accepts an inspector function that has same arguments as the VkPlayLiveWs.WritePong
func (mmWritePong *mVkPlayLiveWsMockWritePong) Inspect(f func()) *mVkPlayLiveWsMockWritePong {
	if mmWritePong.mock.inspectFuncWritePong != nil {
		mmWritePong.mock.t.Fatalf("Inspect function is already set for VkPlayLiveWsMock.WritePong")
	}

	mmWritePong.mock.inspectFuncWritePong = f

	return mmWritePong
}

// Return sets up results that will be returned by VkPlayLiveWs.WritePong
func (mmWritePong *mVkPlayLiveWsMockWritePong) Return(err error) *VkPlayLiveWsMock {
	if mmWritePong.mock.funcWritePong != nil {
		mmWritePong.mock.t.Fatalf("VkPlayLiveWsMock.WritePong mock is already set by Set")
	}

	if mmWritePong.defaultExpectation == nil {
		mmWritePong.defaultExpectation = &VkPlayLiveWsMockWritePongExpectation{mock: mmWritePong.mock}
	}
	mmWritePong.defaultExpectation.results = &VkPlayLiveWsMockWritePongResults{err}
	mmWritePong.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmWritePong.mock
}

// Set uses given function f to mock the VkPlayLiveWs.WritePong method
func (mmWritePong *mVkPlayLiveWsMockWritePong) Set(f func() (err error)) *VkPlayLiveWsMock {
	if mmWritePong.defaultExpectation != nil {
		mmWritePong.mock.t.Fatalf("Default expectation is already set for the VkPlayLiveWs.WritePong method")
	}

	if len(mmWritePong.expectations) > 0 {
		mmWritePong.mock.t.Fatalf("Some expectations are already set for the VkPlayLiveWs.WritePong method")
	}

	mmWritePong.mock.funcWritePong = f
	mmWritePong.mock.funcWritePongOrigin = minimock.CallerInfo(1)
	return mmWritePong.mock
}

// Times sets number of times VkPlayLiveWs.WritePong should be invoked
func (mmWritePong *mVkPlayLiveWsMockWritePong) Times(n uint64) *mVkPlayLiveWsMockWritePong {
	if n == 0 {
		mmWritePong.mock.t.Fatalf("Times of VkPlayLiveWsMock.WritePong mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmWritePong.expectedInvocations, n)
	mmWritePong.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmWritePong
}

func (mmWritePong *mVkPlayLiveWsMockWritePong) invocationsDone() bool {
	if len(mmWritePong.expectations) == 0 && mmWritePong.defaultExpectation == nil && mmWritePong.mock.funcWritePong == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmWritePong.mock.afterWritePongCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmWritePong.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// WritePong implements mm_vk_play_live.VkPlayLiveWs
func (mmWritePong *VkPlayLiveWsMock) WritePong() (err error) {
	mm_atomic.AddUint64(&mmWritePong.beforeWritePongCounter, 1)
	defer mm_atomic.AddUint64(&mmWritePong.afterWritePongCounter, 1)

	mmWritePong.t.Helper()

	if mmWritePong.inspectFuncWritePong != nil {
		mmWritePong.inspectFuncWritePong()
	}

	if mmWritePong.WritePongMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWritePong.WritePongMock.defaultExpectation.Counter, 1)

		mm_results := mmWritePong.WritePongMock.defaultExpectation.results
		if mm_results == nil {
			mmWritePong.t.Fatal("No results are set for the VkPlayLiveWsMock.WritePong")
		}
		return (*mm_results).err
	}
	if mmWritePong.funcWritePong != nil {
		return mmWritePong.funcWritePong()
	}
	mmWritePong.t.Fatalf("Unexpected call to VkPlayLiveWsMock.WritePong.")
	return
}

// WritePongAfterCounter returns a count of finished VkPlayLiveWsMock.WritePong invocations
func (mmWritePong *VkPlayLiveWsMock) WritePongAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWritePong.afterWritePongCounter)
}

// WritePongBeforeCounter returns a count of VkPlayLiveWsMock.WritePong invocations
func (mmWritePong *VkPlayLiveWsMock) WritePongBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWritePong.beforeWritePongCounter)
}

// MinimockWritePongDone returns true if the count of the WritePong invocations corresponds
// the number of defined expectations
func (m *VkPlayLiveWsMock) MinimockWritePongDone() bool {
	if m.WritePongMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.WritePongMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.WritePongMock.invocationsDone()
}

// MinimockWritePongInspect logs each unmet expectation
func (m *VkPlayLiveWsMock) MinimockWritePongInspect() {
	for _, e := range m.WritePongMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to VkPlayLiveWsMock.WritePong")
		}
	}

	afterWritePongCounter := mm_atomic.LoadUint64(&m.afterWritePongCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.WritePongMock.defaultExpectation != nil && afterWritePongCounter < 1 {
		m.t.Errorf("Expected call to VkPlayLiveWsMock.WritePong at\n%s", m.WritePongMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWritePong != nil && afterWritePongCounter < 1 {
		m.t.Errorf("Expected call to VkPlayLiveWsMock.WritePong at\n%s", m.funcWritePongOrigin)
	}

	if !m.WritePongMock.invocationsDone() && afterWritePongCounter > 0 {
		m.t.Errorf("Expected %d calls to VkPlayLiveWsMock.WritePong at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.WritePongMock.expectedInvocations), m.WritePongMock.expectedInvocationsOrigin, afterWritePongCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *VkPlayLiveWsMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCloseInspect()

			m.MinimockInitInspect()

			m.MinimockReadMessageInspect()

			m.MinimockWritePongInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *VkPlayLiveWsMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *VkPlayLiveWsMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCloseDone() &&
		m.MinimockInitDone() &&
		m.MinimockReadMessageDone() &&
		m.MinimockWritePongDone()
}
