// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// VkPlayLiveApiMock implements mm_vk_play_live.VkPlayLiveApi
type VkPlayLiveApiMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetUserID          func(ctx context.Context, userName string) (i1 int, err error)
	funcGetUserIDOrigin    string
	inspectFuncGetUserID   func(ctx context.Context, userName string)
	afterGetUserIDCounter  uint64
	beforeGetUserIDCounter uint64
	GetUserIDMock          mVkPlayLiveApiMockGetUserID

	funcGetWsToken          func(ctx context.Context) (s1 string, err error)
	funcGetWsTokenOrigin    string
	inspectFuncGetWsToken   func(ctx context.Context)
	afterGetWsTokenCounter  uint64
	beforeGetWsTokenCounter uint64
	GetWsTokenMock          mVkPlayLiveApiMockGetWsToken
}

// NewVkPlayLiveApiMock returns a mock for mm_vk_play_live.VkPlayLiveApi
func NewVkPlayLiveApiMock(t minimock.Tester) *VkPlayLiveApiMock {
	m := &VkPlayLiveApiMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetUserIDMock = mVkPlayLiveApiMockGetUserID{mock: m}
	m.GetUserIDMock.callArgs = []*VkPlayLiveApiMockGetUserIDParams{}

	m.GetWsTokenMock = mVkPlayLiveApiMockGetWsToken{mock: m}
	m.GetWsTokenMock.callArgs = []*VkPlayLiveApiMockGetWsTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mVkPlayLiveApiMockGetUserID struct {
	optional           bool
	mock               *VkPlayLiveApiMock
	defaultExpectation *VkPlayLiveApiMockGetUserIDExpectation
	expectations       []*VkPlayLiveApiMockGetUserIDExpectation

	callArgs []*VkPlayLiveApiMockGetUserIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VkPlayLiveApiMockGetUserIDExpectation specifies expectation struct of the VkPlayLiveApi.GetUserID
type VkPlayLiveApiMockGetUserIDExpectation struct {
	mock               *VkPlayLiveApiMock
	params             *VkPlayLiveApiMockGetUserIDParams
	paramPtrs          *VkPlayLiveApiMockGetUserIDParamPtrs
	expectationOrigins VkPlayLiveApiMockGetUserIDExpectationOrigins
	results            *VkPlayLiveApiMockGetUserIDResults
	returnOrigin       string
	Counter            uint64
}

// VkPlayLiveApiMockGetUserIDParams contains parameters of the VkPlayLiveApi.GetUserID
type VkPlayLiveApiMockGetUserIDParams struct {
	ctx      context.Context
	userName string
}

// VkPlayLiveApiMockGetUserIDParamPtrs contains pointers to parameters of the VkPlayLiveApi.GetUserID
type VkPlayLiveApiMockGetUserIDParamPtrs struct {
	ctx      *context.Context
	userName *string
}

// VkPlayLiveApiMockGetUserIDResults contains results of the VkPlayLiveApi.GetUserID
type VkPlayLiveApiMockGetUserIDResults struct {
	i1  int
	err error
}

// VkPlayLiveApiMockGetUserIDOrigins contains origins of expectations of the VkPlayLiveApi.GetUserID
type VkPlayLiveApiMockGetUserIDExpectationOrigins struct {
	origin         string
	originCtx      string
	originUserName string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUserID *mVkPlayLiveApiMockGetUserID) Optional() *mVkPlayLiveApiMockGetUserID {
	mmGetUserID.optional = true
	return mmGetUserID
}

// Expect sets up expected params for VkPlayLiveApi.GetUserID
func (mmGetUserID *mVkPlayLiveApiMockGetUserID) Expect(ctx context.Context, userName string) *mVkPlayLiveApiMockGetUserID {
	if mmGetUserID.mock.funcGetUserID != nil {
		mmGetUserID.mock.t.Fatalf("VkPlayLiveApiMock.GetUserID mock is already set by Set")
	}

	if mmGetUserID.defaultExpectation == nil {
		mmGetUserID.defaultExpectation = &VkPlayLiveApiMockGetUserIDExpectation{}
	}

	if mmGetUserID.defaultExpectation.paramPtrs != nil {
		mmGetUserID.mock.t.Fatalf("VkPlayLiveApiMock.GetUserID mock is already set by ExpectParams functions")
	}

	mmGetUserID.defaultExpectation.params = &VkPlayLiveApiMockGetUserIDParams{ctx, userName}
	mmGetUserID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUserID.expectations {
		if minimock.Equal(e.params, mmGetUserID.defaultExpectation.params) {
			mmGetUserID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUserID.defaultExpectation.params)
		}
	}

	return mmGetUserID
}

// ExpectCtxParam1 sets up expected param ctx for VkPlayLiveApi.GetUserID
func (mmGetUserID *mVkPlayLiveApiMockGetUserID) ExpectCtxParam1(ctx context.Context) *mVkPlayLiveApiMockGetUserID {
	if mmGetUserID.mock.funcGetUserID != nil {
		mmGetUserID.mock.t.Fatalf("VkPlayLiveApiMock.GetUserID mock is already set by Set")
	}

	if mmGetUserID.defaultExpectation == nil {
		mmGetUserID.defaultExpectation = &VkPlayLiveApiMockGetUserIDExpectation{}
	}

	if mmGetUserID.defaultExpectation.params != nil {
		mmGetUserID.mock.t.Fatalf("VkPlayLiveApiMock.GetUserID mock is already set by Expect")
	}

	if mmGetUserID.defaultExpectation.paramPtrs == nil {
		mmGetUserID.defaultExpectation.paramPtrs = &VkPlayLiveApiMockGetUserIDParamPtrs{}
	}
	mmGetUserID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUserID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUserID
}

// ExpectUserNameParam2 sets up expected param userName for VkPlayLiveApi.GetUserID
func (mmGetUserID *mVkPlayLiveApiMockGetUserID) ExpectUserNameParam2(userName string) *mVkPlayLiveApiMockGetUserID {
	if mmGetUserID.mock.funcGetUserID != nil {
		mmGetUserID.mock.t.Fatalf("VkPlayLiveApiMock.GetUserID mock is already set by Set")
	}

	if mmGetUserID.defaultExpectation == nil {
		mmGetUserID.defaultExpectation = &VkPlayLiveApiMockGetUserIDExpectation{}
	}

	if mmGetUserID.defaultExpectation.params != nil {
		mmGetUserID.mock.t.Fatalf("VkPlayLiveApiMock.GetUserID mock is already set by Expect")
	}

	if mmGetUserID.defaultExpectation.paramPtrs == nil {
		mmGetUserID.defaultExpectation.paramPtrs = &VkPlayLiveApiMockGetUserIDParamPtrs{}
	}
	mmGetUserID.defaultExpectation.paramPtrs.userName = &userName
	mmGetUserID.defaultExpectation.expectationOrigins.originUserName = minimock.CallerInfo(1)

	return mmGetUserID
}

// Inspect accepts an inspector function that has same arguments as the VkPlayLiveApi.GetUserID
func (mmGetUserID *mVkPlayLiveApiMockGetUserID) Inspect(f func(ctx context.Context, userName string)) *mVkPlayLiveApiMockGetUserID {
	if mmGetUserID.mock.inspectFuncGetUserID != nil {
		mmGetUserID.mock.t.Fatalf("Inspect function is already set for VkPlayLiveApiMock.GetUserID")
	}

	mmGetUserID.mock.inspectFuncGetUserID = f

	return mmGetUserID
}

// Return sets up results that will be returned by VkPlayLiveApi.GetUserID
func (mmGetUserID *mVkPlayLiveApiMockGetUserID) Return(i1 int, err error) *VkPlayLiveApiMock {
	if mmGetUserID.mock.funcGetUserID != nil {
		mmGetUserID.mock.t.Fatalf("VkPlayLiveApiMock.GetUserID mock is already set by Set")
	}

	if mmGetUserID.defaultExpectation == nil {
		mmGetUserID.defaultExpectation = &VkPlayLiveApiMockGetUserIDExpectation{mock: mmGetUserID.mock}
	}
	mmGetUserID.defaultExpectation.results = &VkPlayLiveApiMockGetUserIDResults{i1, err}
	mmGetUserID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUserID.mock
}

// Set uses given function f to mock the VkPlayLiveApi.GetUserID method
func (mmGetUserID *mVkPlayLiveApiMockGetUserID) Set(f func(ctx context.Context, userName string) (i1 int, err error)) *VkPlayLiveApiMock {
	if mmGetUserID.defaultExpectation != nil {
		mmGetUserID.mock.t.Fatalf("Default expectation is already set for the VkPlayLiveApi.GetUserID method")
	}

	if len(mmGetUserID.expectations) > 0 {
		mmGetUserID.mock.t.Fatalf("Some expectations are already set for the VkPlayLiveApi.GetUserID method")
	}

	mmGetUserID.mock.funcGetUserID = f
	mmGetUserID.mock.funcGetUserIDOrigin = minimock.CallerInfo(1)
	return mmGetUserID.mock
}

// When sets expectation for the VkPlayLiveApi.GetUserID which will trigger the result defined by the following
// Then helper
func (mmGetUserID *mVkPlayLiveApiMockGetUserID) When(ctx context.Context, userName string) *VkPlayLiveApiMockGetUserIDExpectation {
	if mmGetUserID.mock.funcGetUserID != nil {
		mmGetUserID.mock.t.Fatalf("VkPlayLiveApiMock.GetUserID mock is already set by Set")
	}

	expectation := &VkPlayLiveApiMockGetUserIDExpectation{
		mock:               mmGetUserID.mock,
		params:             &VkPlayLiveApiMockGetUserIDParams{ctx, userName},
		expectationOrigins: VkPlayLiveApiMockGetUserIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUserID.expectations = append(mmGetUserID.expectations, expectation)
	return expectation
}

// Then sets up VkPlayLiveApi.GetUserID return parameters for the expectation previously defined by the When method
func (e *VkPlayLiveApiMockGetUserIDExpectation) Then(i1 int, err error) *VkPlayLiveApiMock {
	e.results = &VkPlayLiveApiMockGetUserIDResults{i1, err}
	return e.mock
}

// Times sets number of times VkPlayLiveApi.GetUserID should be invoked
func (mmGetUserID *mVkPlayLiveApiMockGetUserID) Times(n uint64) *mVkPlayLiveApiMockGetUserID {
	if n == 0 {
		mmGetUserID.mock.t.Fatalf("Times of VkPlayLiveApiMock.GetUserID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUserID.expectedInvocations, n)
	mmGetUserID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUserID
}

func (mmGetUserID *mVkPlayLiveApiMockGetUserID) invocationsDone() bool {
	if len(mmGetUserID.expectations) == 0 && mmGetUserID.defaultExpectation == nil && mmGetUserID.mock.funcGetUserID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUserID.mock.afterGetUserIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUserID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUserID implements mm_vk_play_live.VkPlayLiveApi
func (mmGetUserID *VkPlayLiveApiMock) GetUserID(ctx context.Context, userName string) (i1 int, err error) {
	mm_atomic.AddUint64(&mmGetUserID.beforeGetUserIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUserID.afterGetUserIDCounter, 1)

	mmGetUserID.t.Helper()

	if mmGetUserID.inspectFuncGetUserID != nil {
		mmGetUserID.inspectFuncGetUserID(ctx, userName)
	}

	mm_params := VkPlayLiveApiMockGetUserIDParams{ctx, userName}

	// Record call args
	mmGetUserID.GetUserIDMock.mutex.Lock()
	mmGetUserID.GetUserIDMock.callArgs = append(mmGetUserID.GetUserIDMock.callArgs, &mm_params)
	mmGetUserID.GetUserIDMock.mutex.Unlock()

	for _, e := range mmGetUserID.GetUserIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmGetUserID.GetUserIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUserID.GetUserIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUserID.GetUserIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetUserID.GetUserIDMock.defaultExpectation.paramPtrs

		mm_got := VkPlayLiveApiMockGetUserIDParams{ctx, userName}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUserID.t.Errorf("VkPlayLiveApiMock.GetUserID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserID.GetUserIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userName != nil && !minimock.Equal(*mm_want_ptrs.userName, mm_got.userName) {
				mmGetUserID.t.Errorf("VkPlayLiveApiMock.GetUserID got unexpected parameter userName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserID.GetUserIDMock.defaultExpectation.expectationOrigins.originUserName, *mm_want_ptrs.userName, mm_got.userName, minimock.Diff(*mm_want_ptrs.userName, mm_got.userName))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUserID.t.Errorf("VkPlayLiveApiMock.GetUserID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUserID.GetUserIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUserID.GetUserIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUserID.t.Fatal("No results are set for the VkPlayLiveApiMock.GetUserID")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmGetUserID.funcGetUserID != nil {
		return mmGetUserID.funcGetUserID(ctx, userName)
	}
	mmGetUserID.t.Fatalf("Unexpected call to VkPlayLiveApiMock.GetUserID. %v %v", ctx, userName)
	return
}

// GetUserIDAfterCounter returns a count of finished VkPlayLiveApiMock.GetUserID invocations
func (mmGetUserID *VkPlayLiveApiMock) GetUserIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserID.afterGetUserIDCounter)
}

// GetUserIDBeforeCounter returns a count of VkPlayLiveApiMock.GetUserID invocations
func (mmGetUserID *VkPlayLiveApiMock) GetUserIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserID.beforeGetUserIDCounter)
}

// Calls returns a list of arguments used in each call to VkPlayLiveApiMock.GetUserID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUserID *mVkPlayLiveApiMockGetUserID) Calls() []*VkPlayLiveApiMockGetUserIDParams {
	mmGetUserID.mutex.RLock()

	argCopy := make([]*VkPlayLiveApiMockGetUserIDParams, len(mmGetUserID.callArgs))
	copy(argCopy, mmGetUserID.callArgs)

	mmGetUserID.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserIDDone returns true if the count of the GetUserID invocations corresponds
// the number of defined expectations
func (m *VkPlayLiveApiMock) MinimockGetUserIDDone() bool {
	if m.GetUserIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserIDMock.invocationsDone()
}

// MinimockGetUserIDInspect logs each unmet expectation
func (m *VkPlayLiveApiMock) MinimockGetUserIDInspect() {
	for _, e := range m.GetUserIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to VkPlayLiveApiMock.GetUserID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUserIDCounter := mm_atomic.LoadUint64(&m.afterGetUserIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserIDMock.defaultExpectation != nil && afterGetUserIDCounter < 1 {
		if m.GetUserIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to VkPlayLiveApiMock.GetUserID at\n%s", m.GetUserIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to VkPlayLiveApiMock.GetUserID at\n%s with params: %#v", m.GetUserIDMock.defaultExpectation.expectationOrigins.origin, *m.GetUserIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUserID != nil && afterGetUserIDCounter < 1 {
		m.t.Errorf("Expected call to VkPlayLiveApiMock.GetUserID at\n%s", m.funcGetUserIDOrigin)
	}

	if !m.GetUserIDMock.invocationsDone() && afterGetUserIDCounter > 0 {
		m.t.Errorf("Expected %d calls to VkPlayLiveApiMock.GetUserID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserIDMock.expectedInvocations), m.GetUserIDMock.expectedInvocationsOrigin, afterGetUserIDCounter)
	}
}

type mVkPlayLiveApiMockGetWsToken struct {
	optional           bool
	mock               *VkPlayLiveApiMock
	defaultExpectation *VkPlayLiveApiMockGetWsTokenExpectation
	expectations       []*VkPlayLiveApiMockGetWsTokenExpectation

	callArgs []*VkPlayLiveApiMockGetWsTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// VkPlayLiveApiMockGetWsTokenExpectation specifies expectation struct of the VkPlayLiveApi.GetWsToken
type VkPlayLiveApiMockGetWsTokenExpectation struct {
	mock               *VkPlayLiveApiMock
	params             *VkPlayLiveApiMockGetWsTokenParams
	paramPtrs          *VkPlayLiveApiMockGetWsTokenParamPtrs
	expectationOrigins VkPlayLiveApiMockGetWsTokenExpectationOrigins
	results            *VkPlayLiveApiMockGetWsTokenResults
	returnOrigin       string
	Counter            uint64
}

// VkPlayLiveApiMockGetWsTokenParams contains parameters of the VkPlayLiveApi.GetWsToken
type VkPlayLiveApiMockGetWsTokenParams struct {
	ctx context.Context
}

// VkPlayLiveApiMockGetWsTokenParamPtrs contains pointers to parameters of the VkPlayLiveApi.GetWsToken
type VkPlayLiveApiMockGetWsTokenParamPtrs struct {
	ctx *context.Context
}

// VkPlayLiveApiMockGetWsTokenResults contains results of the VkPlayLiveApi.GetWsToken
type VkPlayLiveApiMockGetWsTokenResults struct {
	s1  string
	err error
}

// VkPlayLiveApiMockGetWsTokenOrigins contains origins of expectations of the VkPlayLiveApi.GetWsToken
type VkPlayLiveApiMockGetWsTokenExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetWsToken *mVkPlayLiveApiMockGetWsToken) Optional() *mVkPlayLiveApiMockGetWsToken {
	mmGetWsToken.optional = true
	return mmGetWsToken
}

// Expect sets up expected params for VkPlayLiveApi.GetWsToken
func (mmGetWsToken *mVkPlayLiveApiMockGetWsToken) Expect(ctx context.Context) *mVkPlayLiveApiMockGetWsToken {
	if mmGetWsToken.mock.funcGetWsToken != nil {
		mmGetWsToken.mock.t.Fatalf("VkPlayLiveApiMock.GetWsToken mock is already set by Set")
	}

	if mmGetWsToken.defaultExpectation == nil {
		mmGetWsToken.defaultExpectation = &VkPlayLiveApiMockGetWsTokenExpectation{}
	}

	if mmGetWsToken.defaultExpectation.paramPtrs != nil {
		mmGetWsToken.mock.t.Fatalf("VkPlayLiveApiMock.GetWsToken mock is already set by ExpectParams functions")
	}

	mmGetWsToken.defaultExpectation.params = &VkPlayLiveApiMockGetWsTokenParams{ctx}
	mmGetWsToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetWsToken.expectations {
		if minimock.Equal(e.params, mmGetWsToken.defaultExpectation.params) {
			mmGetWsToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetWsToken.defaultExpectation.params)
		}
	}

	return mmGetWsToken
}

// ExpectCtxParam1 sets up expected param ctx for VkPlayLiveApi.GetWsToken
func (mmGetWsToken *mVkPlayLiveApiMockGetWsToken) ExpectCtxParam1(ctx context.Context) *mVkPlayLiveApiMockGetWsToken {
	if mmGetWsToken.mock.funcGetWsToken != nil {
		mmGetWsToken.mock.t.Fatalf("VkPlayLiveApiMock.GetWsToken mock is already set by Set")
	}

	if mmGetWsToken.defaultExpectation == nil {
		mmGetWsToken.defaultExpectation = &VkPlayLiveApiMockGetWsTokenExpectation{}
	}

	if mmGetWsToken.defaultExpectation.params != nil {
		mmGetWsToken.mock.t.Fatalf("VkPlayLiveApiMock.GetWsToken mock is already set by Expect")
	}

	if mmGetWsToken.defaultExpectation.paramPtrs == nil {
		mmGetWsToken.defaultExpectation.paramPtrs = &VkPlayLiveApiMockGetWsTokenParamPtrs{}
	}
	mmGetWsToken.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetWsToken.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetWsToken
}

// Inspect accepts an inspector function that has same arguments as the VkPlayLiveApi.GetWsToken
func (mmGetWsToken *mVkPlayLiveApiMockGetWsToken) Inspect(f func(ctx context.Context)) *mVkPlayLiveApiMockGetWsToken {
	if mmGetWsToken.mock.inspectFuncGetWsToken != nil {
		mmGetWsToken.mock.t.Fatalf("Inspect function is already set for VkPlayLiveApiMock.GetWsToken")
	}

	mmGetWsToken.mock.inspectFuncGetWsToken = f

	return mmGetWsToken
}

// Return sets up results that will be returned by VkPlayLiveApi.GetWsToken
func (mmGetWsToken *mVkPlayLiveApiMockGetWsToken) Return(s1 string, err error) *VkPlayLiveApiMock {
	if mmGetWsToken.mock.funcGetWsToken != nil {
		mmGetWsToken.mock.t.Fatalf("VkPlayLiveApiMock.GetWsToken mock is already set by Set")
	}

	if mmGetWsToken.defaultExpectation == nil {
		mmGetWsToken.defaultExpectation = &VkPlayLiveApiMockGetWsTokenExpectation{mock: mmGetWsToken.mock}
	}
	mmGetWsToken.defaultExpectation.results = &VkPlayLiveApiMockGetWsTokenResults{s1, err}
	mmGetWsToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetWsToken.mock
}

// Set uses given function f to mock the VkPlayLiveApi.GetWsToken method
func (mmGetWsToken *mVkPlayLiveApiMockGetWsToken) Set(f func(ctx context.Context) (s1 string, err error)) *VkPlayLiveApiMock {
	if mmGetWsToken.defaultExpectation != nil {
		mmGetWsToken.mock.t.Fatalf("Default expectation is already set for the VkPlayLiveApi.GetWsToken method")
	}

	if len(mmGetWsToken.expectations) > 0 {
		mmGetWsToken.mock.t.Fatalf("Some expectations are already set for the VkPlayLiveApi.GetWsToken method")
	}

	mmGetWsToken.mock.funcGetWsToken = f
	mmGetWsToken.mock.funcGetWsTokenOrigin = minimock.CallerInfo(1)
	return mmGetWsToken.mock
}

// When sets expectation for the VkPlayLiveApi.GetWsToken which will trigger the result defined by the following
// Then helper
func (mmGetWsToken *mVkPlayLiveApiMockGetWsToken) When(ctx context.Context) *VkPlayLiveApiMockGetWsTokenExpectation {
	if mmGetWsToken.mock.funcGetWsToken != nil {
		mmGetWsToken.mock.t.Fatalf("VkPlayLiveApiMock.GetWsToken mock is already set by Set")
	}

	expectation := &VkPlayLiveApiMockGetWsTokenExpectation{
		mock:               mmGetWsToken.mock,
		params:             &VkPlayLiveApiMockGetWsTokenParams{ctx},
		expectationOrigins: VkPlayLiveApiMockGetWsTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetWsToken.expectations = append(mmGetWsToken.expectations, expectation)
	return expectation
}

// Then sets up VkPlayLiveApi.GetWsToken return parameters for the expectation previously defined by the When method
func (e *VkPlayLiveApiMockGetWsTokenExpectation) Then(s1 string, err error) *VkPlayLiveApiMock {
	e.results = &VkPlayLiveApiMockGetWsTokenResults{s1, err}
	return e.mock
}

// Times sets number of times VkPlayLiveApi.GetWsToken should be invoked
func (mmGetWsToken *mVkPlayLiveApiMockGetWsToken) Times(n uint64) *mVkPlayLiveApiMockGetWsToken {
	if n == 0 {
		mmGetWsToken.mock.t.Fatalf("Times of VkPlayLiveApiMock.GetWsToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetWsToken.expectedInvocations, n)
	mmGetWsToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetWsToken
}

func (mmGetWsToken *mVkPlayLiveApiMockGetWsToken) invocationsDone() bool {
	if len(mmGetWsToken.expectations) == 0 && mmGetWsToken.defaultExpectation == nil && mmGetWsToken.mock.funcGetWsToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetWsToken.mock.afterGetWsTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetWsToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetWsToken implements mm_vk_play_live.VkPlayLiveApi
func (mmGetWsToken *VkPlayLiveApiMock) GetWsToken(ctx context.Context) (s1 string, err error) {
	mm_atomic.AddUint64(&mmGetWsToken.beforeGetWsTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmGetWsToken.afterGetWsTokenCounter, 1)

	mmGetWsToken.t.Helper()

	if mmGetWsToken.inspectFuncGetWsToken != nil {
		mmGetWsToken.inspectFuncGetWsToken(ctx)
	}

	mm_params := VkPlayLiveApiMockGetWsTokenParams{ctx}

	// Record call args
	mmGetWsToken.GetWsTokenMock.mutex.Lock()
	mmGetWsToken.GetWsTokenMock.callArgs = append(mmGetWsToken.GetWsTokenMock.callArgs, &mm_params)
	mmGetWsToken.GetWsTokenMock.mutex.Unlock()

	for _, e := range mmGetWsToken.GetWsTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmGetWsToken.GetWsTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetWsToken.GetWsTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmGetWsToken.GetWsTokenMock.defaultExpectation.params
		mm_want_ptrs := mmGetWsToken.GetWsTokenMock.defaultExpectation.paramPtrs

		mm_got := VkPlayLiveApiMockGetWsTokenParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetWsToken.t.Errorf("VkPlayLiveApiMock.GetWsToken got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetWsToken.GetWsTokenMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetWsToken.t.Errorf("VkPlayLiveApiMock.GetWsToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetWsToken.GetWsTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetWsToken.GetWsTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmGetWsToken.t.Fatal("No results are set for the VkPlayLiveApiMock.GetWsToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmGetWsToken.funcGetWsToken != nil {
		return mmGetWsToken.funcGetWsToken(ctx)
	}
	mmGetWsToken.t.Fatalf("Unexpected call to VkPlayLiveApiMock.GetWsToken. %v", ctx)
	return
}

// GetWsTokenAfterCounter returns a count of finished VkPlayLiveApiMock.GetWsToken invocations
func (mmGetWsToken *VkPlayLiveApiMock) GetWsTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetWsToken.afterGetWsTokenCounter)
}

// GetWsTokenBeforeCounter returns a count of VkPlayLiveApiMock.GetWsToken invocations
func (mmGetWsToken *VkPlayLiveApiMock) GetWsTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetWsToken.beforeGetWsTokenCounter)
}

// Calls returns a list of arguments used in each call to VkPlayLiveApiMock.GetWsToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetWsToken *mVkPlayLiveApiMockGetWsToken) Calls() []*VkPlayLiveApiMockGetWsTokenParams {
	mmGetWsToken.mutex.RLock()

	argCopy := make([]*VkPlayLiveApiMockGetWsTokenParams, len(mmGetWsToken.callArgs))
	copy(argCopy, mmGetWsToken.callArgs)

	mmGetWsToken.mutex.RUnlock()

	return argCopy
}

// MinimockGetWsTokenDone returns true if the count of the GetWsToken invocations corresponds
// the number of defined expectations
func (m *VkPlayLiveApiMock) MinimockGetWsTokenDone() bool {
	if m.GetWsTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetWsTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetWsTokenMock.invocationsDone()
}

// MinimockGetWsTokenInspect logs each unmet expectation
func (m *VkPlayLiveApiMock) MinimockGetWsTokenInspect() {
	for _, e := range m.GetWsTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to VkPlayLiveApiMock.GetWsToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetWsTokenCounter := mm_atomic.LoadUint64(&m.afterGetWsTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetWsTokenMock.defaultExpectation != nil && afterGetWsTokenCounter < 1 {
		if m.GetWsTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to VkPlayLiveApiMock.GetWsToken at\n%s", m.GetWsTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to VkPlayLiveApiMock.GetWsToken at\n%s with params: %#v", m.GetWsTokenMock.defaultExpectation.expectationOrigins.origin, *m.GetWsTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetWsToken != nil && afterGetWsTokenCounter < 1 {
		m.t.Errorf("Expected call to VkPlayLiveApiMock.GetWsToken at\n%s", m.funcGetWsTokenOrigin)
	}

	if !m.GetWsTokenMock.invocationsDone() && afterGetWsTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to VkPlayLiveApiMock.GetWsToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetWsTokenMock.expectedInvocations), m.GetWsTokenMock.expectedInvocationsOrigin, afterGetWsTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *VkPlayLiveApiMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetUserIDInspect()

			m.MinimockGetWsTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *VkPlayLiveApiMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *VkPlayLiveApiMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetUserIDDone() &&
		m.MinimockGetWsTokenDone()
}
